### ISSUE TITLE
Warn user or create way to deal with relative plans in summarize_plan

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/bluesky#1010]
Using `print_summary()` or `summarize_plan()` with relative scan plans or relative stub plans doesn't reflect what is going to be performed by the run engine.  I believe this is known.

However, a novice bluesky user may not recognize that and change a plan to make the `print_summary` output look correct and then a big problem results when the start the plan.  Hopefully it is just involves running into a limit, but on a more complicated instrument, you could crash something or in general waste a lot of time.

If it is too difficult to make `print_summary` accommodate relative scan plans, then please print a big, obvious warning at the end of the output if any relative plans or relative stub plans are detected.

**Comment by tacaswell** [comment]
What devices were you having trouble with specifically?  

It seems things that have a `.position` attribute work correctly and things that do not are where this come up.

**Comment by ambarb** [comment]
I don't recall specifically, but I have seen this behavior at 23ID-1 and 2ID.   I didn't actually run the scan, but then saw it happen to someone else and thought we should ask.  Now I see.  

23ID would have most likely been something related to theta, delta, gamma, sx, sy, sz.    sy and sz are the only ones that aren't EpicsMotor devices

At 2ID, I have no idea what it was, but it was an EpicsMotor device.  I don't remember which ones I noticed on, but I remember the one that caused some confusion for others was dc.z

**Comment by tacaswell** [comment]
@ambarb can you take a look at https://github.com/NSLS-II/bluesky/pull/1014 ?
