### ISSUE TITLE
Move content from Blue Sky Demo notebook into docs

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#102]
Most of this has already been salvaged, but at least one thing -- Tom's awesome fly scan plot -- has not. Once we get it all, we should nuke the notebook, which is way behind the current API and not as good a teaching tool as a the docs.

**Comment by danielballan** [comment]
The fly scan plot has been superceded by LiveRaster, and everything in that "Blue Sky Demo" notebook is wildly behind the current API. Reopen if you want to give into the git history to revive some part of this.

**Comment by ericdill** [comment]
> everything in that "Blue Sky Demo" notebook is wildly behind the current API

Isn't that true of most of the stuff in the bluesky_git_repo/examples folder?

**Comment by ericdill** [comment]
(because if so, should we do something about this examples folder?)

**Comment by danielballan** [comment]
Based on a quick look, the examples scripts still look useful and working to me. Most are months more recent that the notebook, which IIRC has not been significantly changed since Day 3 of bluesky development.

**Comment by ericdill** [comment]
Ah ok. Any objections to removing the outdated notebook?
