### ISSUE TITLE
python 3.5 segfaulting on travis

### ISSUE THREAD

**Issue by tacaswell** [NSLS-II/bluesky#1027]
Check the version of dependancies

https://travis-ci.org/NSLS-II/bluesky/builds/368602338

The 3.5 build used to pass, failed when restarted.

## Steps to Reproduce (for bugs)

1.
2.
3.

**Comment by mrakitin** [comment]
Also observed in #1001.

**Comment by tacaswell** [comment]
This seems to have fixed its self.
