### ISSUE TITLE
LiveImage BEC

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/bluesky#1041]
Would it be possible for BEC to show live images?

## Expected Behavior
BEC displays live images

## Current Behavior
It does not

## Context
This would be helpful for having a one-stop-shop for plotting.

**Comment by tacaswell** [comment]
While we do have access to all of the required documents now, generically we may not be able to access the files yet (ex non-swmr hdf5, things not being shifted to the right place yet, lags in the file system, the collection computer not having access to the file system....), may not have the right handlers available, and there are concerns about performance (synchronous disk access in the collection loop).  

Generically I don't think we want to show images automatically.

I would probably merge an improved 'LiveImage` callback though.
