### ISSUE TITLE
Why has plan_args default from scan changed?

### ISSUE THREAD

**Issue by jrmlhermitte** [NSLS-II/bluesky#1071]
Metadata provided by scan now is missing a `start` and `stop`:
https://github.com/NSLS-II/bluesky/blob/master/bluesky/plans.py#L813

In version v1.0.0, it used to be present:
https://github.com/NSLS-II/bluesky/blob/v1.0.0/bluesky/plans.py#L236

This has caused a small bug at the CMS beamline, which had a callback (saving to olog) that assumed this field existed. Any reason why this change has been made?

**Comment by danielballan** [comment]
Yes. This was an accidental/undocumented consequence of refactoring `scan` to be just `inner_product_scan`. The information is there, but in a different place, per @mrakitin.

**Comment by jrmlhermitte** [comment]
thanks, went through this issue too quick on basecamp, reading it more carefully, it's pretty clear. I'll make a note on basecamp (our internal system for managing projects). The issue here was that we had a callback running in a thread that assumed metadata had the previous form (`start['plan_args']['start']`) but now has new form (`start['plan_args']['args'][0]`)
