### ISSUE TITLE
[SIX] Uncomplete configuration of RIXSCAM device: cannot use XIP1 plugin

### ISSUE THREAD

**Issue by bisogni** [NSLS-II/bluesky#1078]
RIXSCAM device is not correctly configure to use the XIP1 plugin provided by the XCAM company to extract the centroided positions.
``
In [304]: RE(bpp.pchain(count([rixscam], md={'reason':'dummy'}),count([rixscam], md={'reason':'HR test 5 sec '})))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/.ipython/profile_collection/plans/03-plan.py in <module>()
----> 1 RE(bpp.pchain(count([rixscam], md={'reason':'dummy'}),count([rixscam], md={'reason':'HR test 5 sec '})))

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    742                     # it (unless it is a canceled error)
    743                     if exc is not None:
--> 744                         raise exc
    745 
    746             if self._interrupted:

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/run_engine.py in _run(self)
   1251             self.log.error("Run aborted")
   1252             self.log.error("%r", err)
-> 1253             raise err
   1254         finally:
   1255             # Some done_callbacks may still be alive in other threads.

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/run_engine.py in _run(self)
   1138                     else:
   1139                         try:
-> 1140                             msg = self._plan_stack[-1].send(resp)
   1141                         # We have exhausted the top generator
   1142                         except StopIteration:

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in __call__(self, plan)
   1261         plan = monitor_during_wrapper(plan, self.monitors)
   1262         plan = baseline_wrapper(plan, self.baseline)
-> 1263         return (yield from plan)

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in baseline_wrapper(plan, devices, name)
   1116         return (yield from plan)
   1117     else:
-> 1118         return (yield from plan_mutator(plan, insert_baseline))
   1119 
   1120 

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    136                     continue
    137                 else:
--> 138                     raise ex
    139         # if inserting / mutating, put new generator on the stack
    140         # and replace the current msg with the first element from the

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     89             ret = result_stack.pop()
     90             try:
---> 91                 msg = plan_stack[-1].send(ret)
     92             except StopIteration as e:
     93                 # discard the exhausted generator

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    757     plan1 = plan_mutator(plan, insert_after_open)
    758     plan2 = plan_mutator(plan1, insert_before_close)
--> 759     return (yield from plan2)
    760 
    761 

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    136                     continue
    137                 else:
--> 138                     raise ex
    139         # if inserting / mutating, put new generator on the stack
    140         # and replace the current msg with the first element from the

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     89             ret = result_stack.pop()
     90             try:
---> 91                 msg = plan_stack[-1].send(ret)
     92             except StopIteration as e:
     93                 # discard the exhausted generator

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    136                     continue
    137                 else:
--> 138                     raise ex
    139         # if inserting / mutating, put new generator on the stack
    140         # and replace the current msg with the first element from the

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     89             ret = result_stack.pop()
     90             try:
---> 91                 msg = plan_stack[-1].send(ret)
     92             except StopIteration as e:
     93                 # discard the exhausted generator

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in fly_during_wrapper(plan, flyers)
    815     plan1 = plan_mutator(plan, insert_after_open)
    816     plan2 = plan_mutator(plan1, insert_before_close)
--> 817     return (yield from plan2)
    818 
    819 

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    136                     continue
    137                 else:
--> 138                     raise ex
    139         # if inserting / mutating, put new generator on the stack
    140         # and replace the current msg with the first element from the

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     89             ret = result_stack.pop()
     90             try:
---> 91                 msg = plan_stack[-1].send(ret)
     92             except StopIteration as e:
     93                 # discard the exhausted generator

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    136                     continue
    137                 else:
--> 138                     raise ex
    139         # if inserting / mutating, put new generator on the stack
    140         # and replace the current msg with the first element from the

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     89             ret = result_stack.pop()
     90             try:
---> 91                 msg = plan_stack[-1].send(ret)
     92             except StopIteration as e:
     93                 # discard the exhausted generator

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in pchain(*args)
    234     rets = deque()
    235     for p in args:
--> 236         rets.append((yield from p))
    237     return tuple(rets)
    238 

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/plans.py in count(detectors, num, delay, md)
     65                                       num=num, delay=delay))
     66 
---> 67     return (yield from inner_count())
     68 
     69 

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/utils.py in dec_inner(*inner_args, **inner_kwargs)
   1011                 plan = gen_func(*inner_args, **inner_kwargs)
   1012                 plan = wrapper(plan, *args, **kwargs)
-> 1013                 return (yield from plan)
   1014             return dec_inner
   1015         return dec

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in stage_wrapper(plan, devices)
    906         return (yield from plan)
    907 
--> 908     return (yield from finalize_wrapper(inner(), unstage_devices()))
    909 
    910 

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in finalize_wrapper(plan, final_plan, pause_for_debug)
    467     cleanup = True
    468     try:
--> 469         ret = yield from plan
    470     except GeneratorExit:
    471         cleanup = False

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in inner()
    903 
    904     def inner():
--> 905         yield from stage_devices()
    906         return (yield from plan)
    907 

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in stage_devices()
    896     def stage_devices():
    897         for d in devices:
--> 898             yield Msg('stage', d)
    899 
    900     def unstage_devices():

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    161         try:
    162             # yield out the 'current message' and collect the return
--> 163             inner_ret = yield msg
    164         except GeneratorExit:
    165             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    161         try:
    162             # yield out the 'current message' and collect the return
--> 163             inner_ret = yield msg
    164         except GeneratorExit:
    165             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    161         try:
    162             # yield out the 'current message' and collect the return
--> 163             inner_ret = yield msg
    164         except GeneratorExit:
    165             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    161         try:
    162             # yield out the 'current message' and collect the return
--> 163             inner_ret = yield msg
    164         except GeneratorExit:
    165             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    161         try:
    162             # yield out the 'current message' and collect the return
--> 163             inner_ret = yield msg
    164         except GeneratorExit:
    165             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/run_engine.py in _run(self)
   1195                         # exceptions (coming in via throw) can be
   1196                         # raised
-> 1197                         new_response = yield from coro(msg)
   1198 
   1199                     # special case `CancelledError` and let the outer

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/bluesky/run_engine.py in _stage(self, msg)
   2202         if not hasattr(obj, 'stage'):
   2203             return []
-> 2204         result = obj.stage()
   2205         self._staged.add(obj)  # add first in case of failure below
   2206         yield from self._reset_checkpoint_state_coro()

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/ophyd/areadetector/trigger_mixins.py in stage(self)
    119     def stage(self):
    120         self._acquisition_signal.subscribe(self._acquire_changed)
--> 121         super().stage()
    122 
    123     def unstage(self):

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/ophyd/areadetector/base.py in stage(self, *args, **kwargs)
    161         except RuntimeError as err:
    162             self.unstage(*args, **kwargs)
--> 163             raise err
    164         return ret
    165 

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/ophyd/areadetector/base.py in stage(self, *args, **kwargs)
    158         ret = super().stage(*args, **kwargs)
    159         try:
--> 160             self.validate_asyn_ports()
    161         except RuntimeError as err:
    162             self.unstage(*args, **kwargs)

/opt/conda_envs/collection-2018-2.0/lib/python3.6/site-packages/ophyd/areadetector/base.py in validate_asyn_ports(self)
    259                                'include the source plugin or reconfigure '
    260                                'to not use these ports.'
--> 261                                ''.format(missing_plugins))
    262 
    263     def missing_plugins(self):

RuntimeError: The asyn ports ['XIP1'] are used by plugins that ophyd is aware of but the source plugin is not.  Please reconfigure your device to include the source plugin or reconfigure to not use these ports.
''

**Comment by awalter-bnl** [comment]
Hi @bisogni, how important is this to get fixed? This is a common error to do with Area- detector plugins, without going into to much detail there is a 'plugin' chain being set that ophyd can't work out.

I should be able to fix this issue within an 1-2 hours, so if you would like it done prior to the shutdown let me know.

**Comment by tacaswell** [comment]
I think this has been fixed at the beamline.
