### ISSUE TITLE
BestEffortCallback with Integer Hints

### ISSUE THREAD

**Issue by teddyrendahl** [NSLS-II/bluesky#1097]
## Description
I realize that you are in a re-write of `BEC` but figure I'd point this out anyways. We have a device where one of the `"hints"` is an integer, `BEC` has poor best effort. It creates a figure then yells a warning about how we can not plot `"Omitting .. because it is an integer"`. I have two questions:

1. Was it a mistake not to include `"integer"` as a type we can plot?
2. If there is a good reason for not plotting integer hints. Does it have to complain so loudly? And does it have to make a `matplotlib.Figure` that will never be populated? I'd kind of rather have it silently go about its business.

https://github.com/NSLS-II/bluesky/blob/6ac67b298f4cbafd2ec6762ab71b46ae368a9557/bluesky/callbacks/best_effort.py#L268

**Comment by tacaswell** [comment]
1. Yes which make 2. moot.

**Comment by teddyrendahl** [comment]
Worth putting in a PR or not with https://github.com/NSLS-II/bluesky/pull/1076 in sight?

**Comment by danielballan** [comment]
I think not. I expect the next release will have the new callbacks in it. It's been stalled for months due to travel and then deployment, but we're making daily progress now.

Let's leave this issue open, of course, to remind us to fix it in the new version.
