### ISSUE TITLE
AreaDetector device is not robust to invalid setting (typo)

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/bluesky#1100]
`RE(mv(cam_dev.cam.acquire_time, 0))` produces an error state in the Prosilica ioc because 0 is invalid for the exposure time.  We were unable to change the exposure time through bsui.
```Another set() call is still in progress```

We changed the value in CSS and the ioc removed the alarm state from the PV.  HOwever, bsui (expectedly) still had a set() in progress for the PV.  Restarting bsui corrected the situation, but should this be more robustly handled, aside from a timeout?

**Comment by tacaswell** [comment]
Yes, but this is an ophyd bug.
