### ISSUE TITLE
redundant matplotlib in bluesky.callbacks.core

### ISSUE THREAD

**Issue by pavoljuhas** [NSLS-II/bluesky#1103]
Whilst testing the databroker-elasticsearch callback prototype I found that I need matplotlib to import bluesky callbacks.  There was a prior commit a36eb964 to make `matplotlib` optional, but the code still requires matplotlib later on in the mpl_plotting module.

As of df6b93641c93de157165ebe1559c68e85b0f29b2 `pyflakes` report quite a few unused imports in `callbacks.core`:
```sh
$ pyflakes core.py
core.py:6: 'collections.ChainMap' imported but unused
core.py:10: 'numpy as np' imported but unused
core.py:17: 'matplotlib' imported but unused
core.py:19: '.mpl_plotting.LiveScatter' imported but unused
core.py:19: '.mpl_plotting.LivePlot' imported but unused
core.py:19: '.mpl_plotting.LiveGrid' imported but unused
core.py:19: '.mpl_plotting.LiveFitPlot' imported but unused
core.py:19: '.mpl_plotting.LiveRaster' imported but unused
core.py:19: '.mpl_plotting.LiveMesh' imported but unused
```

@danielballan @tacaswell  - Mind if I clean these up and make the matplotlib presence truly optional?

**Comment by tacaswell** [comment]
Thanks @pavoljuhas , I opened #1104 to fix this.
