### ISSUE TITLE
Send message-related exceptions up through the generator

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#119]
That way, they will raise in the generator instead of the run loop, indicating where the illegal message orginated.

**Comment by tacaswell** [comment]
I don't fully remember what we were talking about here.

**Comment by danielballan** [comment]
We were talking about `.send`-ing IllegalMessageSequence and IllegalMessage up through the generator.

**Comment by danielballan** [comment]
Closed by #298
