### ISSUE TITLE
Add an Event stream that records interruptions (pause, resume, suspend)

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#126]
Two ways to do this:

1. Make one Event Descriptor with a data key for each kind of record ('pause', 'resume', 'suspend', 'unsuspend')

2. Make several Event Descriptors, one per kind of record we want to store. Give it no data keys. Thus, its Events have no data -- only their Event time. Mark the Event Descriptors as being "pause" or "resume" records in some new field like "kind."

**Comment by danielballan** [comment]
I am leaning toward approach (1) -- a single EventDescriptor. This is, roughly speaking, a timestamped history of the state of the RunEngine. There's nothing asynchronous about that, so it should be a single Event stream.

@tacaswell?

**Comment by tacaswell** [comment]
I also prefer 1.

Having a second optional event stream of messages would also be useful.

**Comment by danielballan** [comment]
Closed by #463
