### ISSUE TITLE
hdf5 and tiff export via RunStop callback

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#13]
```
def hdf5_export(template):
    def callback(run_stop):
       filename = template.format(**header)
```

**Comment by tacaswell** [comment]
Also see suitcase

**Comment by danielballan** [comment]
See http://nbviewer.ipython.org/gist/anonymous/a3ee62067986e73b2d2b, which demonstrates automatic TIFF export. This should make its way into the sphinx documentation before we close the issue.

**Comment by danielballan** [comment]
This is documented.
