### ISSUE TITLE
Notes from visit to SRX

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#143]
SRX's needs:

* [x] Energy scan pseudomotor moves monochrometer (Bragg angle, crystal offset) and undulator (one parameter, but a complicated triggering scheme)
* [x] Mesh scan, including "snake" trajectory
* [x] Raster scan the slit: a Python-based slit soft motor
* [x] Filestore reader for HDF5 files that put all data into a single dataset.
* [x] On granularity on Events: each (x, y) point should be an Event because eventually there will be a third dimension (energy). Typical dimensions currently are 80x80 points; eventual dream is many megapixels. Dwell times per point will be ~10ms.

**Comment by tacaswell** [comment]
The first and third may be localized objects.
