### ISSUE TITLE
plotting behavior

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/bluesky#149]
gs.PLOT_y = 'sm_r'

is accepted.  Should have an error return.

subsequent scans should plot on the same figure

**Comment by tacaswell** [comment]
Why should `gs.PLOT_y = 'sm_r'` be an error?

**Comment by ambarb** [comment]
@danielballan suggested this when the above typo was entered into bluesky instead of gs.PLOT_Y = 'sm_r' . I believe he already implemented something to prevent users from creating nonexistent gs.PLOT_

**Comment by tacaswell** [comment]
Ah, typo on the left, not on the right.

**Comment by danielballan** [comment]
This is harder than I thought because `GlobalState` subclasses `HasTraits`. Maybe not worth the complexity or the trouble.
