### ISSUE TITLE
Scan validation, Take 2

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/bluesky#151]
Scan validation that scientists actually would use...

`gs.toy_RE(scan_obj)` for the OO API

`gs.dryrun = False` for the simple scan API

In either case, RunEngine will *always* print a BIG message (at each prompt!!) warning that data is not being collected at the beginning and the end.

1. Syntax errors in the scan
2. Illegal message sequence in the scan
3. Motors asked to exceed their limits (especially commanding pseudomotors where this is not self-evident)
4. Pie in the sky: trajectories and dynamical check of the geometries and experimental conditions in general (collision detection, is my beam hitting the sample)

**Comment by ambarb** [comment]
^ @danielballan is typing here, so blame him (me) for that snakyness.

**Comment by danielballan** [comment]
Note: Today this came up at HXN as well.

**Comment by danielballan** [comment]
New thought on this: a simple `dry_run` kwarg might be simplest and most explicit. It would automatically work in both the SPEC-like and normal APIs.

`RE(scan, dry_run=True)`

or

`ct(dry_run=True)  # kwarg unknown to ct is passed through to RunEngine`

**Comment by ambarb** [comment]
As we get closer to having reciprocal space calculations and more complicated crystals/diffraction geometries, it would also be great to also have this feature to check for bad diffraction geometries (i.e. wrong or poorly selected incident and reflected beam angles from sample and also parts of 3 and 4 from above). The beam angle relative to the sample surface can affect the quality/reliability of the data.

**Comment by danielballan** [comment]
Use Cases 1-3 have been addressed and are now documented in an example (under review [here](https://github.com/NSLS-II/docs/pull/52)). Use Case 4 (collision detection) and the additional case noted in @ambarb's comment just above are much larger projects and out of scope for bluesky. They would have to be addressed in conjunction with external libraries like our [hklpy](https://github.com/NSLS-II/hklpy), which could provide simulated motors that perform the necessary computations but do not move hardware.

As far as I know it is not an immediate priority for anyone, but when the time comes we can open a new issue there.
