### ISSUE TITLE
conda-recipe deps

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/bluesky#159]
Do we need to include pcaspy somewhere in the conda-recipe? It is in the run_tests.py module

**Comment by danielballan** [comment]
I think you can include test dependencies. Maybe? My strategy so far has
been to put test deps in Travis but not in the conda recipe. I don't want
bluesky to depend on epics.

**Comment by ericdill** [comment]
Ah, let me circle back to this issue now that I have had much more experience with conda and conda-build.  The answer to my initial question is 'no'. We do not need to include pcaspy in the meta.yaml because we never execute `run_tests.py` as part of the recipe.

My apologies that you put in a PR to fix this issue.  I would suggest *not* adding pcaspy to the test requirements.

**Comment by danielballan** [comment]
Interesting. Well I learned something. :- )
