### ISSUE TITLE
Handle exceptions from user-specified Futures

### ISSUE THREAD

**Issue by klauer** [NSLS-II/bluesky#175]
In my fly-scan kick-off method, I run the scanning routine in an executor which, of course, returns a future. If that routine raises an exception, I would expect bluesky to handle it by marking the scan as aborted and dumping me back to the interpreter so I can debug the problem.

Two possibilities I see are:
1. Register `Future`s with the `RunEngine` to be checked somehow (during `wait`, in my case).
2. Put more information into the `DetectorStatus` object (with exception information, making it pretty much a `Future`).

Kickoff method for reference, which re-raises the exception:

```python
    def kickoff(self, *args):
        self._status = FlyStatus()

        def run_fly():
            try:
                self._collect_data = self._execute(*args)
            except Exception:
                self._failed = True
                raise
            finally:
                self._status._finished()

        loop.run_in_executor(None, run_fly)
        return self._status
```

Currently, the exception is not handled until the end of the IPython session, with the message 
```
Future exception was never retrieved
```

**Comment by danielballan** [comment]
A third (not necessarily better) possibility:

```
fut = loop.run_in_executor(None, run_fly)
return fut, self._status
```

I usually don't like it when functions return tuples that have no obvious order, but it's an option.

- Danbot, totally not Dan himself, who is on vacation and would never think about work while on vacation

**Comment by klauer** [comment]
I guess an argument for @danielballanbot's  option is that the `DetectorStatus` completion doesn't _necessarily_ coincide with the successful completion of the `Future`.

I may have missed out on some key meetings that explain why it's a horrible idea, but I rather like the thought of `DetectorStatus` being a `Future` instead.

> In [1]: danbot.query_happiness()

**Comment by danielballan** [comment]
Interesting. Offhand I can't think of a reason why it couldn't be, so long as we can arrange the same careful timing at instantiation time.

>Out[1]: True!!! (or NaN, whichever is funnier)

**Comment by klauer** [comment]
Bumping this issue. It didn't gain much traction initially, so it makes me wonder if I am completely off-base in this request?

**Comment by tacaswell** [comment]
This is just something subtle that we have not had time to deal with yet.

**Comment by danielballan** [comment]
+1, good idea, may happen during this cycle

**Comment by danielballan** [comment]
> I may have missed out on some key meetings that explain why it's a horrible idea, but I rather like the thought of `DetectorStatus` being a `Future` instead.

One nice thing about having a special object serving as a bridge is that It isolates the implementation details of the RunEngine from the implementation details of the hardware object. It does not import asyncio, which means the library that defines the hardware object does not have to import asyncio.

That said, you point to a compelling case where the object should return a proper asyncio `Future`. And the idea of *mixing* those with our custom status objects seems more confusing and complex than just using `Future` objects for everything.

Thoughts @dchabot, @tacaswell?

**Comment by tacaswell** [comment]
It wouldn't be too hard to do dispatch in BS, but I think it would introduce a very large surface for bugs.

Maybe a better way to go here is to add a `_failed` method to the status objects which I think we can use as a bridge to re-raise these exceptions in the main loop.

**Comment by danielballan** [comment]
> Maybe a better way to go here is to add a _failed method to the status objects

This happened. Is the issue resolved, @klauer? I think some of the early discussion danced around conflating the two different kinds of coroutines in play here.

**Comment by tacaswell** [comment]
If the status objects finish with out succeeding the the RE sticks a `FailedStatus` exception into it's `_exception` field which carries the `Status` object as it's payload, however there is not any way to automatically ask that object if it has an exception it would like be re-raised instead.

**Comment by klauer** [comment]
I'm not seeing this issue anymore. Soft-pausing and resuming works with hxn fly scans (at least, in-between sub-scans = checkpoints). Closing for now.
