### ISSUE TITLE
Peak stats

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/bluesky#178]
Notes from quick chat with @cmazzoli. CSX would really really like 1 & 2 when the beam comes back. 3-5 are less important, but would be much appreciated

## peak stats
1. make peak stats programmatically accessible via some sort of local variable
2. print table of peak stats when run is over [e.g.] (https://github.com/NSLS-II-CHX/chxtools/blob/master/chxtools/ophyd_tools.py#L10)
3. cen() <-- moves the last motor to the peak stats center of mass
4. plot peak stats when run is over 
  - optional, if plotting, make what is plotted optional
  - plot vertical line for peak center
5. plot peaks stats live while run is happening

**Comment by ericdill** [comment]
I didnt see this anywhere else, so let me know if this is already covered by something/someone else

**Comment by klauer** [comment]
I think you would make @skalbfleisch very happy with number 3.

**Comment by danielballan** [comment]
@ericdill It came up with @cmazzoli (as you know, of course) but we do not seem to have created an issue. It's safe to say we intend to have `cen()` by the time the beam is back.

**Comment by danielballan** [comment]
Modulo a hilarious argument about colors, this is done and working on real data.
