### ISSUE TITLE
Put history on PyPI

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#182]
Without that, bluesky setup.py fails without history being installed.

**Comment by tacaswell** [comment]
`history` needs to be renamed before we make it public.  Maybe to `hdict`?

#257 makes it optional from the BS PoV as we don't pip install it internally and `standard_config.py` (the only place we import history) is full of site-specific junk anyway.

**Comment by danielballan** [comment]
Or `historydict`? +1 for making it optional. We should rip out `standard_config.py` ASAP.

**Comment by ericdill** [comment]
I'm not clear how #257 has put history on pypi

**Comment by danielballan** [comment]
I guess @tacaswell considers the issue closed from bluesky's point of view, but I don't mind leaving this open as a reminder.

**Comment by tacaswell** [comment]
This is closed because the problem of `pip install bluesky` not working is fixed.

If we want to track the need to put history on pypi, it should be tracked in history's bugs, not here.

**Comment by danielballan** [comment]
For the record, this is done. https://pypi.python.org/pypi/historydict
