### ISSUE TITLE
Reorganizing files

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#189]
A note from @klauer prompted me to write down my preferences for reorganizing the package as it grows:

- [x] `*_callbacks.py` -> `callbacks/` sub-package or external package
- [x] `register_mds.py` -> metadatastore or (if simple enough) just do this in the IPython profile directly
- [x]  `hardware_checklist.py`, and `standard_config.py` -> separate package / just delete them
- [x] `qt_kicker.py` -> utils.py

**Comment by danielballan** [comment]
On second thought maybe `register_mds` belongs in `callbacks/`. Meh.

**Comment by klauer** [comment]
Seems like a logical spot for it.

**Comment by danielballan** [comment]
As per @arkilic's request (and my preference) we'll put the schema files in a language-agnostic repo of their own, where metadataclient, bluesky, and any future projects can share them.

**Comment by arkilic** [comment]
:tada:

**Comment by danielballan** [comment]
If we add a function the metadatstore/client with the following signature:

```python
insert(name, doc)  # name could also be 'bulk_events' in which doc is a list of docs
```

then all of `register_mds.py` could be replaced by:

```python
from metadata[store/client] import insert
RE.subscribe_lossless('all', insert)
```

**Comment by arkilic** [comment]
Still need to add tests but here it is: https://github.com/NSLS-II/metadataclient/pull/8

**Comment by danielballan** [comment]
Sweet. Thanks for the fast turn-around.

**Comment by danielballan** [comment]
This is all done.
