### ISSUE TITLE
bluesky/scientific_callbacks.PeakStats

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/bluesky#199]
the `cen` bit of PeakStats needs to have some exception handling in the two cases where it will not work:

1. When there is only one point
1. When two points are identical

Note that these might not actually be issues, but they should be checked.

**Comment by ericdill** [comment]
This is from an in-person conversation with @tacaswell re: getting a demo ready for the SAC on Monday

**Comment by tacaswell** [comment]
Done https://github.com/NSLS-II/bluesky/blob/master/bluesky/scientific_callbacks.py#L8
