### ISSUE TITLE
Callback for filestore validation

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#22]
First-order: Make sure nothing raises `DatumNotFound`
Second-order: Validate and then hash contents and save attributes in new FS collection.

**Comment by danielballan** [comment]
First-order solution implemented in XPD's IPython profile. This should be added to bluesky:

```
# We probably already have these imports, but we use them below
# so I'm importing here to be sure.
from databroker import DataBroker as db, get_events


def verify_files_accessible(name, doc):
    "This is a brute-force approach. We retrieve all the data."
    ttime.sleep(0.1)  # Wati for data to be saved.
    if name != 'stop':
        return
    print("  Verifying that run was saved to broker...")
    try:
        header = db[doc['run_start']]
    except Exception as e:
        print("  Verification Failed! Error: {0}".format(e))
        return
    else:
        print('\x1b[1A\u2713')
    print("  Verifying that all data is accessible on the disk...")
    try:
        list(get_events(header, fill=True))
    except Exception as e:
        print("  Verification Failed! Error: {0}".format(e))
    else:
        print('\x1b[1A\u2713')
```

**Comment by cowanml** [comment]
Wouldn't this be better in FileStore?

fs_validate(header, validation_params)

or something.
Could be done server side if FileStore gets servicified.

could optionally/configurably check:
   file size within some range (0byte files are a fairly common failure mode
   owner, group, perms
   whatever

return list of failures and failure mode for each?

-matt

**Comment by danielballan** [comment]
Sure, that sounds reasonable. PRs welcome! :- )
