### ISSUE TITLE
scan id print out missing from scan launch text

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/bluesky#256]
The scanid used to print out on the screen when a scan is launched at the top of the data table. That doesn't happen anymore.

**Comment by danielballan** [comment]
This is something beamline scientists can (and are generally hoped to...) customize on their own.

Start with this and customize it to your liking. Add it to your IPython profile, any place after `gs.RE` has been defined. The file called `99-whatever.py` is a good bet.

```
def print_at_start(name, doc):
    "Take in 'start' Documents and print scan IDs."
    print('Scan ID: ', doc['scan_id'])
    print('Unique ID: ', doc['uid'])

gs.RE.subscribe('start', print_at_start)
```

**Comment by ambarb** [comment]
Ok. I understand. But we had it working last week so I don't understand why that would have changed.  We will investigate further. Thanks.

**Comment by danielballan** [comment]
Weird. Keep me posted. Thanks.

**Comment by ambarb** [comment]
There was a slightly different issue later with the live-plot during data collection. creating a new figure with "figure" did not result in live plot resuming.  quitting and restarting bluesky fixed the live-plot issue and the one above (print out of the scanid after scan launch).

**Comment by danielballan** [comment]
Interesting. Without more information I doubt I can figure this one out. Soon we will be storing verbose log files from all the beamlines, and at that point there might be some hope of performing forensics.

I'll close the issue for now -- don't hesitate to reopen if you have more information.
