### ISSUE TITLE
Allow the automated logbook entries to be customizable

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/bluesky#264]
@lwiegart at CHX is requesting that the automated logbook entries be customizable.  He would like to see the first line of the log entry be the scan_id followed by the scan command that was invoked in the IPython repl.  The first line would then look something like:

`234 dscan(dcm_b, -4, 4, 50, .004, com='dcm bragg scan')`

or

`235 ct(5, com='direct beam position ont he Eiger 4M')`

**Comment by tacaswell** [comment]
I have partially done code to do this by default, for now they quickest path is to set `RE.logbook = None` and then write a run start callback that does the logging to olog.  All of the information you need to do the above (well, almost, you can not know the names of the motor objects in the global namespace) right now.

**Comment by ericdill** [comment]
Fun, hacky solution that I just implemented at CHX: https://github.com/NSLS-II-CHX/ipython_ophyd/commit/ec0bcd5981cb9349b3cdaa570f843f49650bedd1

**Comment by ericdill** [comment]
Let the rotten tomato throwing commence :)

**Comment by danielballan** [comment]
Neat! I actually really like this subscription. The olog functionality is already tightly coupled to IPython (via %logit) so it doesn't hurt to rely on IPython in a second way here.

I recall @stuwilkins wanted something like this: a quick reminder of what the user actually typed is often very useful. Our fully-expanded, maximally-reproducible representation of the command is also good to have, but it's not such a good a memory-jogging tool. This is.

**Comment by ericdill** [comment]
> so it doesn't hurt to rely on IPython in a second way here.

Well yeah, and also this is done in the ipython startup directory, so we are already pretty clearly in IPython here :smile:

**Comment by ericdill** [comment]
Glad you are +1!

**Comment by tacaswell** [comment]
meh, it's dirty but so is 90% of the global state.  I have plans to start teaching beamline staff / users how to write scans that will have many starts per call at the command line (a 'macro' as it were) so there will need to be a bit more thought on how to manage that (yay more state!).

**Comment by ericdill** [comment]
I mean it's pretty easy to shove in a different log formatter when a RunStart document is received. You might just consider writing a custom logger?

**Comment by danielballan** [comment]
@tacaswell I thought of that. The behavior here would not be very confusing. Multiple runs would say they were generated by one command. The point here isn't to provide a reproducible command; it's to provide a quick reminder of what was being done.
