### ISSUE TITLE
What happens when you abort a dscan?

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/bluesky#266]
When you abort a dscan does it return the motor to its original position?

cc @lwiegart

**Comment by danielballan** [comment]
No. Soon (next cycle) you will be able to set cleanup instructions for any exit condition (success, error, user-initiated abort).

**Comment by danielballan** [comment]
To elaborate, it's not clear which behavior is more desirable. In most conditions, the user probably wants the motors returned. But if the scan is aborted because of a dangerous condition, the user wants the motors to stop where they are.

**Comment by cowanml** [comment]
'abort' sounds like it should stop everything.  Crtl-c should
behave that way.

There could be a 'cancel' that just stops the current measurement and
configurably returns to it's start point or not.  And maybe a 'rewind'
that moves back to the start, which you could use after 'abort' when
you really meant 'cancel'.

And then 'wait_wait_wait__no__that_was_ok__I_just_panicked__please_continue'
(it's more clear than 'undo_cancel_or_abort' :)

**Comment by danielballan** [comment]
@cowanml In the terminology of bluesky, I think you and I agree on the following:

* 'abort' : Stop everything where it is. Record run as 'aborted'. This is what Ctrl+C Ctrl+C does.
* 'stop': Return motors to their positions. Record run as 'success'. This was Ctrl+C `RE.stop()` does.
* 'pause': Stop everything where it is. Allow user to decide if they want to abort or stop. This is where the "rewinding" comes in.

**Comment by danielballan** [comment]
Original question was answered [above](https://github.com/NSLS-II/bluesky/issues/266#issuecomment-158156414). More control over abort/stop/pause behavior will be developed as part of #243.
