### ISSUE TITLE
Base implementations of `trigger` and `set`

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#279]
Take this example:

```python
class Thing(Device):
    a = Component(EpicsSignal, '...')
```

This cannot be used with bluesky's built-in plans because calls to `trigger` raise an error. As a reminder `Device.trigger` handles the common case where one of the components is a "trigger" that needs to be sent a `trigger_value`. If no components specify a `trigger_value`, the user is forced to implement a no-op trigger like so:

```python
class Thing(Device):
    a = Component(EpicsSignal, '...')
    def trigger(self):
        status = StatusObject()
        status._finished()
        return status
```

Options I can think of:
1. current situation, which is workable but I think annoying for simple devices that have no trigger
2. use a no-op trigger when there is no `trigger_value` (potentially confusing -- users might not realize `trigger` is a no-op
2. to be more explicit, accept a class-level like `triggerable = False` that invokes a no-op `trigger`
 
   ```python
    class Thing(Device):
        triggerable = False
        a = Component(EpicsSignal, '...')
```

3. don't implement a `trigger` in `Device` at all
4. implement a no-op `trigger` in `Device`

I don't have a clear preference right now, but I think we should try to setting this tomorrow. Thoughts?

**Comment by tacaswell** [comment]
I vote for the 2nd number 2 via a PR to implement it.

**Comment by klauer** [comment]
I don't like options 3, 4, or 5 at all.
I dislike 1 and 2 less...

**Comment by danielballan** [comment]
@tacaswell @klauer That leaves the question of what to do this `set`.

I want `motor.set(5)` to continue to work. Beyond that I don't really care how it's implemented.
