### ISSUE TITLE
Another looming API issue: 'set' is a contested term

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#308]
While I'm in the business of re-writing the Msg API in #294, let's consider another lurking issue: apparently "set" means "set zero point" to SPEC users like @cmazzoli. Last summer, @stuwilkins warned @tacaswell and I against adopting "set" as bluesky terminology. This has come up as a point of confusion a couple times since. Does anyone know whether this is common terminology in hardware control generally or mainly a SPEC thing?

When we do add support for setting zero points, I would prefer something explicit like `set_zero` or `zeropoint`.

As for "set" itself, should we:
* carry on with `Msg('set', ...)`, asking scientists to forget SPEC's meaning of "set" and learn ours
* relent, and do a name change in bluesky and ophyd like

    ```
    s/Msg('set'/Msg('SOMETHING_ELSE'/
    s/def set(/def SOMETHING_ELSE(/
    s/\.set(/.SOMETHING_ELSE(/
    ```

Candidates for SOMETHING_ELSE:
* 'write', which is a better counterpart to 'read'
* 'move': We avoided this originally to avoid have some isolation from `Positioner.move` and because people don't think about "moving" a temperature controller. I'm not sure "writing" to a temperature controller is much more intuitive, language-wise, and I do think that `move` ~~satisfies the bluesky API at this point.~~ could easily be made to satisfy the bluesky API if it was asynchronous by default. The behavior of `ophyd.commands.mov` and of `obj.move(wait=True)` would not have to change.

**Comment by tacaswell** [comment]
Note, Dan edited the message after the email went out.

**Comment by danielballan** [comment]
The informal committee of @dchabot, @klauer, @tacaswell, and myself have decided we're just going to leave this as it is, barring a popular uprising. Speak now or forever hold your peace.
