### ISSUE TITLE
Port GUI for SRX into a callback-able that works in py3

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#31]

**Comment by danielballan** [comment]
Is this still alive?

**Comment by danielballan** [comment]
attn @ericdill I think

**Comment by ericdill** [comment]
"porting" an enaml app is rewriting it

**Comment by ericdill** [comment]
https://github.com/NSLS-II-SRX/controlsui

**Comment by ericdill** [comment]
and the `mk2` branch would be the one of interest.  That being said, I have not had much contact with garth, so he would need to be looped in.  I would imagine that they already have something like this running on their beamline by now

**Comment by danielballan** [comment]
Is this the same project that @licode is working on now?

**Comment by heroux** [comment]
no. As far as I know Li is not working on a GUI. He will present to us what he will be working on when he has a better idea...1-2 weeks.

**Comment by licode** [comment]
All, I am sorry for not updating enough. I had meetings with srx/hxn , and what they want first is some basic functionalities, such as image alignment, 2D scan based on selected ROI. GUI is probably the thing we may need to worry about when all the functions are ready, also depending on my ongoing discussion with them later. Let's talk more next week.

**Comment by danielballan** [comment]
OK, per @ericdill's comment above, I'm closing this. As mentioned in the last group meeting, @tacaswell and @licode are working on GUI-based selection tools related to this. That will be a separate issue/PR.
