### ISSUE TITLE
control plot_x key

### ISSUE THREAD

**Issue by imrealkaren** [NSLS-II/bluesky#331]
A scan (e.g. ascan) using energy pseudo axis at SRX now uses undulator gap as the default x for live plot.
It needs to be energy. 

A more general question, how to set up x axis for plotting when using ascan, dscan, etc. 
Namely, I do not want to define my own plan, in which can can use this?

> my_plotter = LivePlot('det', 'motor', legend_keys=['sample'])
> RE(my_scan, my_plotter)

**Comment by imrealkaren** [comment]
And shall I be concerned with the message
"Failed to stop Energy(prefix='', name='energy', read_attrs=['uv', 'bragg', 'c_gap', 'move_uv', 'move_cgap'], configuration_attrs=['uv', 'move_uv', 'move_cgap'], monitor_attrs=[])"?

I've tried using both ascan and just run the AbsScanPlan in RE. Same error message.

**Comment by danielballan** [comment]
@tacaswell Are either of these still relevant after your work today? The second issue ("failed to stop...") probably means you did not define a `stop` method on the `Energy` pseudo-positioner.

**Comment by klauer** [comment]
Before I forget - @imrealkaren wants PLOT_X for spec-like scans that functions similarly to PLOT_Y

**Comment by tacaswell** [comment]
It is a `Device` so it should get a stop from that.

**Comment by danielballan** [comment]
And once people start wanting two plots (as CSX just indicated that they do) they'll want PLOT_X1 and PLOT_X2.... I think we need to see if a collection of plans in the beamline config can do the job. A proliferation of `gs.*` is going to get really confusing.

**Comment by klauer** [comment]
X1, X2, etc seems excessive, but given how easy and useful it is to configure PLOT_Y, PLOT_X really seems like a feature that should be there.

**Comment by hhslepicka** [comment]
:+1: on adding just the PLOT_X.

**Comment by danielballan** [comment]
K. Just pushing back for the sake of being conservative. I'm convinced.

**Comment by tacaswell** [comment]
We probably need to start scoping the `gs` namespace.  I think with multilple panel plots we need to move away from `ascan` + special state to named scans/plans the close over a specific set of motors, detectors, and subscriptions.

**Comment by danielballan** [comment]
Given the progress we are making pushing some groups toward OO, I hate to see the SPEC-style API bloat before we even have the chance to teach the good API.

**Comment by danielballan** [comment]
Let me phrase my last comment differently....

Providing lots of nobs for customizing `ascan` seems more difficult for users than supporting a couple different scans -- `ascan_slits`, `ascan_diff_eta`, etc. Bluesky can't ship all thoes varieties, but I think we can build them in beamline configs, plugging in the appropriate subscriptions in each case. Once we address the ~10 scans that beamlines perform, will there be much demand to mutating their settings through `gs`?

**Comment by danielballan** [comment]
The PLOT_Y key is gone now and, with it, the needs for this. This is now addressed by the 'hints' feature.
