### ISSUE TITLE
suspender should prevent new scan to be launched

### ISSUE THREAD

**Issue by imrealkaren** [NSLS-II/bluesky#356]
As it is now, suspender is in the event loop to prevent next event being taken.
However, it should also prevent new scan to be launched and start the scan when the threshold being met.

**Comment by danielballan** [comment]
This is a useful request. We did not design suspenders with this use case in mind, but it makes sense that suspenders *should* work this way. Unfortunately this will require a major re-working of how suspenders work so it won't be a quick fix. But I do think it is something we can do in the coming weeks.

**Comment by danielballan** [comment]
Fixed by #396. @imrealkaren Tom will deploy this fix at SRX soon.
