### ISSUE TITLE
An array of 1 for peak stats

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/bluesky#361]
Hooray for ````gs.PS```!  I wonder if com should have the same format a cen and fwhm for consistency. Or if you want to make cen and fwhm an array of 1.  You guys decide.  

````
In [29]: gs.PS.max
Out[29]: (0.50001101694470762, 17846650.0)

In [30]: gs.PS.cen
Out[30]: 1.1269493862857818

In [31]: gs.PS.com
Out[31]: array([ 1.60048895])

In [32]: gs.PS.fwhm
Out[32]: 3.6783402665488296

In [33]: mov(theta,gs.PS.max[0])

   theta              

    0.5000 deg        


In [34]: gs.PS.com[0]
Out[34]: 1.6004889541348961

````

**Comment by danielballan** [comment]
Yep, this was just a mistake. Now fixed in #365. Thanks as usual for the thorough report.

**Comment by ericdill** [comment]
@ambarb this fix will be available from the nsls2-tag channel in about 45 minutes.

```
conda update bluesky -c nsls2-tag --no-deps
```

**Comment by ericdill** [comment]
Err sorry, the nsls2-dev channel...

```
conda update bluesky -c nsls2-dev --no-deps
```
