### ISSUE TITLE
fail to import LiveImage callback from bluesky.broker_callbacks

### ISSUE THREAD

**Issue by imrealkaren** [NSLS-II/bluesky#371]
xray_vision module missing.

```python
BlueSky [5]: from bluesky.broker_callbacks import LiveImage
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-3209614a2784> in <module>()
----> 1 from bluesky.broker_callbacks import LiveImage

/home/xf05id1/.conda/envs/collection/lib/python3.4/site-packages/bluesky/broker_callbacks.py in <module>()
      6 from metadatastore.commands import run_start_given_uid, descriptors_by_start
      7 import matplotlib.pyplot as plt
----> 8 from xray_vision.backend.mpl.cross_section_2d import CrossSection
      9 from .callbacks import CallbackBase
     10 import numpy as np

ImportError: No module named 'xray_vision'

**Comment by ericdill** [comment]
what machine are you on (output of "uname -a")?
what environment are you in? (output of "which conda")
what is currently installed? (output of "conda list -e")

**Comment by ericdill** [comment]
(ignore my questions if someone is already helping you :smile: )

**Comment by imrealkaren** [comment]
(collection)xf05id1@xf05id1-ws2:/nfs/xf05id1/ipython_ophyd$ uname -a
Linux xf05id1-ws2 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u5 x86_64 GNU/Linux
(collection)xf05id1@xf05id1-ws2:/nfs/xf05id1/ipython_ophyd$ which conda
/home/xf05id1/.conda/envs/collection/bin/conda
(collection)xf05id1@xf05id1-ws2:/nfs/xf05id1/ipython_ophyd$ conda list -e
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
backports_abc=0.4=py34_0
bluesky=0.4.1=py34_1
boltons=15.0.0=py34_0
channelarchiver=0.0.5.6.post4=4_gd3e9283_py34
cycler=0.9.0=py34_0
cytoolz=0.7.4=py34_0
databroker=0.3.2.post6=6_g972ef05_py34
decorator=4.0.6=py34_0
doct=1.0.1=py34_0
epics-base=3.14.12.5=0
filestore=0.2.3=py34_0
fontconfig=2.11.1=5
freetype=2.5.5=0
gnureadline=6.3.3.post16=py34_0
h5py=2.5.0=np110py34_4
hdf5=1.8.15.1=2
history=0.0.1.post39=py34_0
historydict=1.0.0.post20=py34_0
humanize=0.5.1=py34_0
ipykernel=4.1.1=py34_0
ipython=4.0.1=py34_0
ipython_genutils=0.1.0=py34_0
ipywidgets=4.1.0=py34_0
jbig=2.1=0
jinja2=2.8=py34_0
jpeg=8d=0
jsonschema=2.4.0=py34_0
jupyter_client=4.1.1=py34_0
jupyter_core=4.0.6=py34_0
keyring=5.3=py34_0
libgfortran=1.0=0
libpng=1.6.17=0
libsodium=1.0.3=0
libtiff=4.0.6=1
libxml2=2.9.2=0
lmfit=0.9.2.post15=15_gee41f80_npNonepy34
markupsafe=0.23=py34_0
matplotlib=1.5.1.post61=61_g513da02_py34
metadatastore=0.3.2=py34_0
mistune=0.7.1=py34_0
mongoengine=0.10.5=py34_2
nbconvert=4.1.0=py34_0
nbformat=4.0.1=py34_0
ncurses=5.9=6
notebook=4.0.6=py34_0
numpy=1.10.2=py34_0
openblas=0.2.14=3
openssl=1.0.2d=0
ophyd=0.2.0.post19=19_g4ff4fdc_py34
pandas=0.17.1=np110py34_0
path.py=8.1.2=py34_1
pexpect=3.3=py34_0
pickleshare=0.5=py34_0
pillow=3.0.0=py34_1
pims=0.3.2.post30=30_g717a2de_py34
pip=7.1.2=py34_0
prettytable=0.7.2=py34_0
ptyprocess=0.5=py34_0
pyepics=3.2.5rc3.post24=24_gdeb37ea_py34
pygments=2.0.2=py34_0
pymongo=3.0.3=py34_0
pyolog=4.0.0.post5+g1a24409=py34_0
pyparsing=2.0.3=py34_0
pyqt=4.11.4=py34_1
python=3.4.4=0
python-dateutil=2.4.2=py34_0
pytz=2015.7=py34_0
pyyaml=3.11=py34_1
pyzmq=15.1.0=py34_0
qt=4.8.7=1
readline=6.2.5=1
requests=2.9.0=py34_0
scipy=0.16.1=np110py34_0
setuptools=19.1.1=py34_0
simplegeneric=0.8.1=py34_0
sip=4.16.9=py34_0
six=1.10.0=py34_0
slicerator=0.9.7=py34_0
sqlite=3.8.4.1=1
super_state_machine=1.0=py34_0
terminado=0.5=py34_1
tifffile=0.7.0=np110py34_1
tk=8.5.18=0
tornado=4.3=py34_0
traitlets=4.0.0=py34_0
tzlocal=1.1.2=py34_0
wheel=0.26.0=py34_1
xz=5.0.5=0
yaml=0.1.6=0
zeromq=4.1.3=0
zlib=1.2.8=0

**Comment by ericdill** [comment]
what does `conda install xray-vision -c nsls2-tag --dry-run` print to the screen?

**Comment by imrealkaren** [comment]
collection)xf05id1@xf05id1-ws2:/nfs/xf05id1/ipython_ophyd$ conda install xray-vision -c nsls2-tag --dry-run
Fetching package metadata: /opt/conda/lib/python3.5/site-packages/requests/packages/urllib3/connection.py:266: SubjectAltNameWarning: Certificate for pergamon.cs.nsls2.local has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
......
Solving package specifications: ......................
Package plan for installation in environment /home/xf05id1/.conda/envs/collection:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    xray-vision-0.0.4.post7    |7_ge6b680f_npNonepy34         136 KB  https://pergamon.cs.nsls2.local:8443/conda/nsls2/linux-64/

The following NEW packages will be INSTALLED:

    xray-vision: 0.0.4.post7-7_ge6b680f_npNonepy34 https://pergamon.cs.nsls2.local:8443/conda/nsls2/linux-64/

Dry run: exiting

**Comment by ericdill** [comment]
Ok that is not going to install any weird dependencies. Go ahead and install xray-vision with that command, just remove the --dry-run, so: `conda install -c nsls2-tag xray-vision`.  After that try to start up ipython and import LiveImage again.

**Comment by imrealkaren** [comment]
Thanks. this is solved and can be closed.

**Comment by ericdill** [comment]
Great! glad it is importable now
