### ISSUE TITLE
A web-based tail -f for logs

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#385]
Add a callback that provides a web-based interface to INFO-level logging, perhaps organized like Travis logs -- instead of one page per build, we could show one page per run or per `RunEngine.__call__`.

**Comment by cowanml** [comment]
On Sun, 13 Mar 2016, Dan Allan wrote:
> Add a callback that provides a web-based interface to INFO-level
> logging, perhaps organized like Travis logs -- instead of one page
> per build, we could show one page per run or per RunEngine.__call__.


If you're going to do any sort of web stuff, I strongly encourage you
to take a long look at:  syncweb, ispyb, exi, etc.  These systems have
been refined and improved over a long time by a large number of people
across numerous facilities.

Also, sensitive (means different things to different people) info has
a tendency to show up in logs.  I highly recommend designing the system
to require individual authentication from the start.

**Comment by danielballan** [comment]
I'm talking about 1-2 hour investment in flask app that shows logs for DAMA and expert beamline staff, not a user-facing website. Everything would run inside the controls firewall.

**Comment by danielballan** [comment]
I don't think I'm personally going to build this. If anyone is interested (cc @stuwilkins?) I'm happy to provide support.
