### ISSUE TITLE
Capture list of subscriptions that were active in MDS.

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#386]
I have mixed feeling about whether this is a good idea, but this is one way that we could record information about user intention at the time the run was executed.

This in information would have to be captured in the RunStop or in a special event stream. We don't know about all 'subscribe' Msgs until the run is closed.

**Comment by klauer** [comment]
I think this is useful information, the only question is how to store it. This could potentially be superseded by implementing #126 with a data stream of all messages in a run (or a subset thereof).

**Comment by tacaswell** [comment]
However, when (hopefully soon) we start making much greater use of out-of-process processing (even for live viz), this will quickly become less useful as the only subscriptions on the RE will be a message bus + MDS.

**Comment by danielballan** [comment]
While implementing the solution we discussed -- see #387 -- I realized that it does not actually solve the problem. Most (but not necessarily all) of the 'subscribe' come in *before* the run is started.

@tacaswell favors stashing this information in the RunStop, while making the point above. Perhaps I should have held my ground more firmly: if users want magical things, they need to give us more information than they gave SPEC.

**Comment by danielballan** [comment]
(So, while #387 does not seem to solve *this* problem, I still think #387 is worthwhile.)

**Comment by danielballan** [comment]
Better idea (also due to @tacaswell): push the job to recording what was done onto the callbacks themselves. So, LivePlot makes a note somewhere (a new wild-west metadatastore collection? analysis store someday? sqlite? text?) that it processed RunStart with a certain uid with such-and-such parameters. (This could be done with a subclass, a decorator, etc.)

**Comment by danielballan** [comment]
I'm going to close this because the solution I proposed requires no changes to bluesky. It would look something like this:

```
class CustomLivePlot(LivePlot):
    "Make a note that this plot was shown."
    def start(self, doc):
        # write into a file or a database (analysisstore, when it exists)
        super().start(doc)  # proceed with more LivePlot stuff
```
