### ISSUE TITLE
Fixing the spec file writer

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/bluesky#391]
There are a few problems with the current implementation of the spec file writer.  I will enumerate them here and submit three separate PRs; one per heading.

## Bad #L line (fixed by #392)
The spec files that are currently being written do not actually work correctly because we are writing extra things on the #L line but not in the data table that immediately follows the #L line.  Example:

```python
from bluesky.tests.utils import setup_test_run_engine
from bluesky.plans import DeltaScanPlan, AbsScanPlan, Count
from bluesky.examples import motor, det, det2
from bluesky.callbacks.core import LiveSpecFile
RE = setup_test_run_engine()
RE.ignore_callback_exceptions = False
!rm out.spec
dscan = DeltaScanPlan([det, det2], motor, -1, 1, 10)
ascan = AbsScanPlan([det, det2], motor, -1, 1, 10)
ct = Count([det])
RE(dscan, [LiveSpecFile('out.spec')])
!cat out.spec
```
and the output:
```
#F out.spec
#E 1458583512.2857118
#D 2016-03-21 14:05:12.285712
#C test_owner  User = test_owner
#O0 No Positioners Were Given

#S 1 dscan motor -1 1  
#D 2016-03-21 14:05:12.285712
#T -1 (Seconds)
#P0 -inf -inf -inf -inf
#N 5
#L motor    Epoch  Seconds  det  det2  motor
0.0  1458583512.4079819 -1 1.0 1.764993805169191
0.2222222222222222  1458583512.725613 -1 0.9756109800648459 1.764993805169191
0.4444444444444444  1458583512.8443232 -1 0.9059551911095096 1.764993805169191
0.6666666666666666  1458583512.9804332 -1 0.8007374029168081 1.764993805169191
0.8888888888888888  1458583513.1254492 -1 0.6736384553447268 1.764993805169191
1.1111111111111112  1458583513.261288 -1 0.5394075072376265 1.764993805169191
1.3333333333333333  1458583513.3805876 -1 0.41111229050718745 1.764993805169191
1.5555555555555554  1458583513.5015962 -1 0.29823409618142166 1.764993805169191
1.7777777777777777  1458583513.6174684 -1 0.20592424643419874 1.764993805169191
2.0  1458583513.732594 -1 0.1353352832366127 1.764993805169191
```

Note that `motor` is listed twice in the `#L` line but only appears once in the data table.  There are six elements on the #L line but only 5 entries in the data table.

## Acquisition time not being represented accurately

Even when you pass in the acquisition time to `dscan` it is not being propagated to the spec file writer.

```python
from bluesky.global_state import gs
from bluesky.spec_api import dscan
from bluesky.examples import motor, det
from bluesky.callbacks import LiveSpecFile
! rm out.spec
specwriter = LiveSpecFile('out.spec')
gs.DETS = [det]
gs.RE.md['owner'] = 'test'
gs.RE.md['group'] = 'test'
gs.RE.md['beamline_id'] = 'test'
gs.RE.md['config'] = {}
dscan(motor, -1, 1, 10, 1, specwriter)
```
uid is
```
['68c03b49-966c-4904-a4ed-577bd4d44b28']
```
and the spec file looks like:
```
#F out.spec
#E 1458584401.9367123
#D 2016-03-21 14:20:01.936712
#C test  User = test
#O0 No Positioners Were Given

#S 6 dscan motor -1 1 (10,) 
#D 2016-03-21 14:20:01.936712
#T -1 (Seconds)
#P0 -inf -inf -inf -inf
#N 4
#L motor    Epoch  Seconds  det  motor
-1.0  1458584402.2141356 -1 0.6065306597126334
-0.8  1458584402.277252 -1 0.7261490370736908
-0.6  1458584402.3425076 -1 0.835270211411272
-0.3999999999999999  1458584402.4054952 -1 0.9231163463866359
-0.19999999999999996  1458584402.472727 -1 0.9801986733067554
0.0  1458584402.5365283 -1 1.0
0.20000000000000018  1458584402.5991907 -1 0.9801986733067553
0.40000000000000013  1458584402.665147 -1 0.9231163463866358
0.6000000000000001  1458584402.7268472 -1 0.835270211411272
0.8  1458584402.7940352 -1 0.7261490370736908
1.0  1458584402.8567617 -1 0.6065306597126334
```

The acquisition time of `1` in the `dscan(motor, -1, 1, 10, 1, specwriter)` invocation is not seen in the scan invocation line (`#S`) and it is showing up as the default value of `-1` in the `#T` line and in the data table.  This appears to be because this information is not being captured in metadatastore.

```python
db['68c03b49-966c-4904-a4ed-577bd4d44b28'].start.plan_args
```
output:
```
{'detectors': '[reader: det]',
 'motor': 'mover: motor',
 'num': '11',
 'start': '-1',
 'stop': '1'}
```

Yikes!  This happens on the live set up at CHX too.  See scan `'fa616713-2397-428c-8a11-92c8da73b94b'`. Lutz says that this was created with the command: `dscan(s1.yc,-.05,.05,5,1)`

## Capturing the position of relevant motors on the beamline before the scan starts

This is essentially the output of `wh_pos`, but formatted for spec's consumption.  There are three places where this needs to be performed.

1. In the header of the spec file (note that the spec file header is distinct from the scan header) with the `#O0` line. This line is the 'human readable' set of motor names
2. Also in the header of the spec file with the `#o0` line. This is the name of the motor that you would type in spec. The equivalent would be the Python variable names in the IPython session
3. In the header of each scan with the `#P` line. This is the current value of the motor. It needs to be in the same order as in `#O` and `#o`.

cc @danielballan @lweigart @afluerasu @vivekthampy

**Comment by danielballan** [comment]
> The acquisition time is not being stored in metadatastore.

Yes. The acquisition time is not in `plan_args` because it is part of the object's configuration, not part of the plan (just like `num_images`, for example). In the SPEC-style API, we do accept a `time` argument. Every device that has a `count_time` attribute gets set to this time. Any devices that don't (including area detectors) are currently ignored. None of this is part of the Plan.

The way forward:

1. Add a `count_time` attribute to all detectors that sets the actual EPICS signals (acquire_time, acquire_period, num_images, ...) appropriately.
2. Include `'count_time'` in the detector's `configuration_attrs` so that it is stored in metadatastore.
3. Program the SPEC callback to read the time from the metadatastore:

```python
# start with some field_name like xray_eye1_stats1_total
obj_name = descriptor['object_names'][field_name]
config = descriptor['configuration'][obj_name]  # the result of obj.read_configuration() was stored here
count_time = config['count_time']
```

> Capturing the position of relevant motors before the scan starts

This information will be recorded in a separate event stream. There is a PR in bluesky waiting to merged at the end of this cycle. Users will probably provide some different list of detectors (and motors) in some new field like `gs.BASELINE_DETS`. For now, I suggest we keep inserting a placeholder and wait to do this right -- first thing at the end of the cycle.

**Comment by danielballan** [comment]
@tacaswell During deployment, did you put a `count_time` signal on the detector(s) at CHX? That would be the last piece of this issue.

**Comment by tacaswell** [comment]
No

**Comment by danielballan** [comment]
Turns out CHX wants to interpret "count_time" as what we can "num" --- not `det.num_images`, but `num` as in the integer argument to `count`. So to them `time` is a dimensionless integer, not something that has units of seconds. To each their own!

This concludes the issues with the SPEC callback mentioned in this issue.
