### ISSUE TITLE
A newly-running run engine should be in 'checkpointed' state.

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#407]

**Comment by tacaswell** [comment]
*grumble* dangerous *grumble*

I'll implement this.

**Comment by ericdill** [comment]
What is the rationale for this?

**Comment by danielballan** [comment]
@ericdill Sorry I missed this question. This was actually suggested by @tacaswell, so I'm confused by his "grumble" above. Anyway, if a scan happens to be interrupted right at the beginning, before it has had a chance to process a 'checkpoint', it dies. If instead it treats the beginning of the plan as a de-facto checkpoint, it can always recover -- no matter when the interruption happens. Users can always issue a 'clear_checkpoint' message if they want to make the scan die upon interruption.

**Comment by danielballan** [comment]
@tacaswell I did this in #407 -- a two-line change plus a bug-fix I found while looking through this.

**Comment by danielballan** [comment]
Closed by #407
