### ISSUE TITLE
Proposal: optional pause and resume methods on Devices

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#415]
On pausing and resuming, the RunEngine could call `device.pause()` and `device.resume()` on all objects that it knows about. This would give objects like flyers or complicated detectors a way to clean themselves up if needed.

I am proposing that this be an optional part of the bluesky interface, not a required method.

Thoughts?

**Comment by klauer** [comment]
I think this is probably a good idea and am also in favor of not bloating the interface further by making these optional.
