### ISSUE TITLE
`step` is unused in `spec_api.tw`...

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/bluesky#483]
Turns out that the `tw()` function isn't actually tested in the bluesky test suite. I'm not entirely sure how to test this function or I'd just add a test and submit a PR.  Note specifically that the `step` positional argument is not used within the function.

**Comment by klauer** [comment]
I believe it's used here:
https://github.com/NSLS-II/bluesky/blob/master/bluesky/plans.py#L2470

User input overrides the given default step. The user input portion is what makes this difficult to test, although overriding the `'input'` command in the RE would work well enough in my opinion.

**Comment by ericdill** [comment]
But the `step` argument from `spec_api.tw` never gets passed to the `plans.tweak` function: https://github.com/NSLS-II/bluesky/blob/master/bluesky/spec_api.py#L385

**Comment by klauer** [comment]
Good catch; you're right.
