### ISSUE TITLE
question: how to record a calculated data field/signal based on other signals in each event?

### ISSUE THREAD

**Issue by imrealkaren** [NSLS-II/bluesky#490]
How do we record a data field/signal that is a calculated value based other signals (motor positions)?

E.g. in our tomography, I'd like to record a field/signal called 'horizontal position', which is a combination of x and z motor positions, depending on the angle, something roughly look like:
h_pos = x_pos\*cos(theta_pos) + z_pos\*sin(theta_pos) + .. (with some constant correction)

The goal is to be able to access the h_pos using get_table, get_event easily.
Additionally, can this h_pos be used as the horizontal axis in the live_raster callback?

Ultimately having a pseudo axis is ideal but being able to test it first is helpful.

**Comment by klauer** [comment]
Something similar to [this](https://github.com/NSLS-II-HXN/ipython_ophyd/blob/master/profile_collection/startup/15-zp.py#L106) could be implemented rather easily. It has x- and z- pseudo axes, which correspond to two real x- and z- axes with a rotary stage (`zpsth`) underneath. `theta0` is a soft signal - a user-configurable offset in case calibration is necessary.

You could then call `pos.forward()` and `pos.reverse()` to just run the calculations and not move any physical motors. Alternatively, a mock `PseudoPositioner` with `SoftPositioner`s in place of the real `EpicsMotors` could allow you to test it directly in scans.

Recording those parameters is as easy as any other `Device` - adding either `configuration_attrs` or `read_attrs`.

**Comment by imrealkaren** [comment]
Thanks a lot @klauer !
It works and we can run scans now using this pseudo motor at SRX
The only non-decorative change I had to make was add the zpsth into the return for the forward function:
```python
    @pseudo_position_argument
    def forward(self, position):
        theta = self.radian_theta
       #.......
#        return self.RealPosition(zpssx=x, zpssz=z) #original
        return self.RealPosition(zpssx=x, zpssz=z, zpsth = math.degrees(theta)) #new
```

If I don't make this change, it would complain about a missing argument. Let me know if this is unexpected.

Another issue is that even though I added all real and pseudo positioners into the pos.read_attrs, only the scanned motion can be shown in a LiveTable and is recorded in the events. What should have I done differently to record all the positioners?
```python
BlueSky [2]: tomo_lab.read_attrs = ['zpssx_lab', 'zpssz_lab', 'zpssx', 'zpssz', 'zpsth']

BlueSky [3]: plan = AbsListScanPlan([], tomo_lab.zpssz_lab, [0, -10, -20, -30])

BlueSky [4]: plan = subs_wrapper(plan, [LiveTable([tomo_lab])])

BlueSky [5]: gs.RE(plan)
+-----------+------------+------------+
|   seq_num |       time |  zpssz_lab |
+-----------+------------+------------+
|         1 | 18:57:06.6 |    -30.005 |
|         2 | 18:57:07.0 |    -30.005 |
|         3 | 18:57:07.5 |     -6.257 |
|         4 | 18:57:07.9 |    -21.967 |
+-----------+------------+------------+
generator list_scan ['add45e'] (scan num: 371)

Out[5]: ['add45e89-c995-4f2c-9a58-86de05f96d44']
BlueSky [9]: evs = list(get_events(db[-1], fill=True))

BlueSky [10]: evs[0].data
Out[10]: {'zpssz_lab': -30.0048221075916}
```

**Comment by klauer** [comment]
@imrealkaren - great, glad it's working! You're right about the `forward()` fix being necessary; I hadn't had a chance to test that new PseudoPositioner just yet.

Regarding recording the additional parameters, the `tomo_lab` would have to become one of your "detectors" passed into the `AbsListScanPlan`. Bluesky will then include every `read_attr` at every scan point.

**Comment by imrealkaren** [comment]
Thanks a lot @klauer . 
I just added it as a detector and it works. We should be able to work out the rest from here!
