### ISSUE TITLE
liveraster unuseful on high-aspect ratio scans

### ISSUE THREAD

**Issue by gjwillms** [NSLS-II/bluesky#544]
We need to perform scans that are of order 10 mm x 10 microns in scale.  LiveRaster insists on a fixed aspect ratio pixel, but as my scan has an aspect ratio of order 1000, the resulting image is useless.  Subclassing LiveRaster and attempting to use ax.set_aspect() creates a plot with the correct size, which is overwritten with a fixed-aspect ratio plot when it is populated with data.  I presume that this means that ax.set_aspect() should be issued between populating the plot and drawing it, rather than where it is currently issued at initialization.  I believe that exposing an aspect ratio option through the LiveRaster interface would be beneficial.

At the moment, I can't plot such scans on the fly.

**Comment by tacaswell** [comment]
```python
class FixedAspect(LiveRaster):
    def start(self, doc):
        super().start(doc)
        self.ax.set_aspect('auto')
```

The call to `imshow` in `start` resets the aspect ratio of the axes.

**Comment by klauer** [comment]
It's nice that a temporary fix is so simple, as @tacaswell shows. @tacaswell just mentioned he's working on fixing this upstream.
