### ISSUE TITLE
Dots in keys

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#572]
Is the fact that '.' is not allowed in a key an implementation detail of mongo or part of the document schema? Tim noticed that portable-mds supports it but of course pymongo does not.

I'm not sure we need to decide this now, but we should at least document the issue. Bluesky or event_model could be made to check for this, but I'm inclined to wait and see where we land on various storage backend options.

**Comment by tacaswell** [comment]
unlikely we will fully expunge mongo, and it is better to keep the same (artificial) restrictions across names everywhere.

dots in names will also mess with `doct`'s ability to get values by attribute access.

**Comment by danielballan** [comment]
Sure, it's easier to relax a restriction than impose one, and mongo queries for headers are here to stay. I'm convinced.

If jsonschema does not support this kind of condition, we will need to change the API between bluesky and event_model.

**Comment by tacaswell** [comment]
See http://stackoverflow.com/a/18313878/380231 for how to put regex restrictions on arbitrary on properties.

**Comment by danielballan** [comment]
So, to summarize, we can and should validate that users have not put any dots in metadata field names by updating the jsonschema files in NSLS-II/event_model. No change to bluesky or to the *Python* code in event_model will be necessary.

@licode Would you be interested in tackling this? It's straightforward and would get you some experience with jsonschema and our event_model repository.

Feel free to say no. :- )

**Comment by licode** [comment]
sounds good to me. I will give it a try.

**Comment by danielballan** [comment]
Track further progress on this issue over at the event-model issue linked above. It should require no changes to bluesky.
