### ISSUE TITLE
Deprecate `sleep` and `input` in favor of non-ambiguous names.

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#578]
Although the [standard config](http://nsls-ii.github.io/fresh-installation.html#create-new-ipython-profile) does not import `bluesky.plans.sleep` or `bluesky.plans.input` into the global namespace, users seem to do it themselves (probably via `from bluesky.plans import *`). We can and should discourage bulk-importing, but I don't think this is enough to remove the potential ambiguity.

How about `sleep` -> `delay` (thanks @hhslepicka) and `input` -> `plan_input`? I would advocate deprecating the existing names very slowly, leaving them in (with warnings) for the next several cycles.

**Comment by hhslepicka** [comment]
```input``` -> ```async_input``` also looks good!

**Comment by tacaswell** [comment]
I like `sleep` -> `nap` :smiling_imp:

**Comment by danielballan** [comment]
Heh. Maybe? The word "delay" is already in our API (as a kwarg to `count`). I could come around to `nap` though. :- )

**Comment by tacaswell** [comment]
```python
def plan():
    yield from nap(5)
    yield from fire_the_missiles()
```

**Comment by danielballan** [comment]
But I am le tired.
