### ISSUE TITLE
matplotlib RuntimeWarning raised after upgrade (2017-1)

### ISSUE THREAD

**Issue by gjwillms** [NSLS-II/bluesky#633]
SRX scan plans now see a warning raised for each instance of LiveRaster.  Plans appear to complete normally.

In [8]: RE(hf2dxrf(xstart=38.418,xstepsize=0.006,xnumstep=5,ystart=6.752,ystepsize=0.006,ynumstep=5,acqtime=.3,numrois=
   ...: 1, i0map_show=True,itmap_show=False,shutter=False))
xstop = 38.448
ystop = 6.782
/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/matplotlib/image.py:371: RuntimeWarning: invalid value encountered in less
  rgba[..., 1] = A < 0  # under data
/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/matplotlib/image.py:372: RuntimeWarning: invalid value encountered in greater
  rgba[..., 2] = A > 1  # over data
+-----------+------------+------------+--------------------------+------------+--------------------------+--------------------+--------------------+------------------------------+
|   seq_num |       time | hf_stage_x | hf_stage_x_user_setpoint | hf_stage_y | hf_stage_y_user_setpoint | current_preamp_ch0 | current_preamp_ch2 | xs_channel1_rois_roi01_value |
+-----------+------------+------------+--------------------------+------------+--------------------------+--------------------+--------------------+------------------------------+
|         1 | 14:09:35.2 |  38.417995 |                38.418000 |   6.752000 |                 6.752000 |        0.000000115 |        0.000000001 |                       0.0000 |

**Comment by tacaswell** [comment]
Tracked upstream as https://github.com/matplotlib/matplotlib/issues/7746

Closing here as this needs to be fixed upstream.
