### ISSUE TITLE
ENH: Run engine subscription gives listified arrays

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/bluesky#636]
Would it be possible for the run engine to give back the actual arrays rather than their list equivalents? This way db.restream(hdr, fill=True) and the run engine give back the same things.

**Comment by tacaswell** [comment]
Yes, we are doing the sanitation in the wrong place.

**Comment by danielballan** [comment]
@CJ-Wright This will get done by us eventually, but if you want it done sooner, this is something I think you could tackle. Copy `sanitize_np` into metadatastore and perform the sanitization there, on insert. Once that's merged in MDS, we can remove all instances of `sanitize_np` from `run_engine.py`, and we're done.

**Comment by CJ-Wright** [comment]
Cool, I might be able to get to this, I am currently working on a defensive filestore call for our live data processing
