### ISSUE TITLE
add 'spiral_square_pattern' to common plans file

### ISSUE THREAD

**Issue by awalter-bnl** [NSLS-II/bluesky#646]
I have written a spiral_square plan (like spiral but follows a square path not a circular path) to 40-ESM_plans.py. It may be useful to move this over to the standard plans. It requires both spiral_square and spiral_square_pattern.

**Comment by danielballan** [comment]
Sweet! Would you like to try forking bluesky and opening a pull request with this code? It should be pasted in plans.py, preferably near the definitions of the other spiral scans.

**Comment by stuartcampbell** [comment]
@danielballan hasn't this been added ? I presume that this issue is just a hangover.

**Comment by tacaswell** [comment]
no #675 is still open due to discussion of exactly how to paraterize it.

**Comment by mrakitin** [comment]
I think it's covered by #1001. @danielballan, are you OK if we close this issue as a duplicate?
