### ISSUE TITLE
Adaptive scan negative direction request

### ISSUE THREAD

**Issue by awalter-bnl** [NSLS-II/bluesky#647]
Can we allow negative direction motion in adaptive_scan?

**Comment by danielballan** [comment]
Yes, this was an unintentional assumption. Will fix in the next release.

**Comment by tacaswell** [comment]
For the EMS uses, we probably want to expose a version of this plan that does not create a run so that they can easily put all of their back-and-forths into a single run (this would solve one of the problem @awalter-bnl and I talked about on friday about how to easily get all of the rows that go together).

**Comment by danielballan** [comment]
@awalter-bnl Any interest in submitting a patch to fix this, as an opportunity to dig into what adaptive plan code looks like?

**Comment by awalter-bnl** [comment]
@danielballan Well I could try but my time is a little short at present. It may take me some time to get around to this.

**Comment by danielballan** [comment]
OK, we'll try to pick this up ourselves. It should be a quick fix. Thanks again for highlighting it.

**Comment by licode** [comment]
OK, I will take care of this.

**Comment by danielballan** [comment]
Closed by #871.

**Comment by danielballan** [comment]
This is also relevant to @sghose: `adaptive_scan` now scans in both positive and negative directions.

**Comment by sghose** [comment]
Great. Is this implemented in the new release of BS or the existing one ( at XPD, 28ID) would work?

**Comment by danielballan** [comment]
The new (yet-to-be-deployed) release.
