### ISSUE TITLE
`num_steps` is a poor name for differentiating intervals vs points

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#652]
Options:

* num_steps and num_intervals (adding num_intervals and leaving the ambiguous name "steps" to mean "points")
* num_points and num_intervals (an API break)
* num_steps == num_points and num_intervals (a redundancy)

Taking the long view, coping with the disruption of an API break in the short term avoids off-by-one errors in the long term. On the other hand, removing num_steps from the documents will surely cause annoying errors at a couple beamlines that we will have to tediously resolve.

**Comment by prjemian** [comment]
* num_steps != num_points 
* num_steps == num_points -1

But,  if terms involving *step* seem unclear, *num_intervals* [worksforme](https://certif.com/spec_help/ascan.html)

**Comment by danielballan** [comment]
Good. Yeah, the SPEC reference is what I was going for there. I want to avoid 'steps' because, unfortunately we've been using num_steps to mean 'number of points' on the floor, and *changing* the meaning of steps by 1 seems worse than removing it altogether.

**Comment by prjemian** [comment]
right.  No one wants to specify steps (as in intervals-1).  Either intervals or stepsize are the natural choices.

**Comment by danielballan** [comment]
To be clear, the changes proposed here and implemented in #673 only change the metadata recorded by the plan, not its inputs.The plan signatures still take 'number of points', intentionally following the numpy convention [np.linspace](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html) over the SPEC one. We *could* accept `num_intervals` and/or `stepsize` as optional keyword-only arguments, but that would make the function signatures harder to interpret. Coupled or mutually exclusive kwargs are a bit of an anti-pattern in Python. So, our position has been that's easy enough for the user to do something like:

```python
def my_scan(detectors, motor, start, stop, stepsize, **kwargs):
    num = (start - stop) // stepsize
    yield from scan(detectors, motor, start, stop, num, **kwargs)
```

Your point is well taken: specifying by step size is natural and popular. It might be worth considering pulling this up into core bluesky one way or another.

**Comment by stuartcampbell** [comment]
Yes, we should decide if what 'default' / base plans we ship and as you say @danielballan maybe include one for step size - then we just need to decide what to do about the last point.

**Comment by tacaswell** [comment]
I vociferously disagree, `num_points == num_steps`, however I seem to be outvoted.
