### ISSUE TITLE
event stream priority

### ISSUE THREAD

**Issue by tacaswell** [NSLS-II/bluesky#658]
Putting this here instead of event model as the hard changes will be to bluesky.

We should add a key to descriptors to give the priority of the stream as a hint to clients.

This is important for facilities that include things we capture via the archiver directly in their primary data artifact (that we then want to expose via the document model).

attn @rayosborn

**Comment by danielballan** [comment]
Funnily enough, my work on the data broker today was leading me intgis direction too. +1 from me.

**Comment by danielballan** [comment]
> We should add a key to descriptors to give the priority of the stream as a hint to clients.

Should this go into 'hints'? Is the priority per-object or per-stream?

**Comment by danielballan** [comment]
This use case is handled by https://github.com/NSLS-II/bluesky/issues/712. Closing with in-person consensus with @tacaswell.
