### ISSUE TITLE
`getattr` in CallbackBase

### ISSUE THREAD

**Issue by ordirules** [NSLS-II/bluesky#688]
This is not a bug. This is a question.

In core.py:
```python
class CallbackBase:
    def __call__(self, name, doc):
        "Dispatch to methods expecting particular doc types."
        return getattr(self, name)(doc)
```

Is this safe? Should we instead check that `name` is valid?
```python
if name in self._allowed_names:
    return getattr(self, name, doc)
```

**Comment by CJ-Wright** [comment]
:+1: This could be particularly problematic for the visualization callbacks which have methods other than document names.

**Comment by danielballan** [comment]
In typical use, the only thing calling `__call__` is the RunEngine's dispatcher, and it always passes in legal names. (They are validated on the way out.) So I think it would be rare to hit this bug and arguably not worth any performance hit on this hot code path.

Other opinions? What do you say, @stuartcampbell?

**Comment by tacaswell** [comment]
If it is not valid it will (correctly) blow up.  I do not think it is worth a check here.
