### ISSUE TITLE
  Check what happens if the same callback is registered twice

### ISSUE THREAD

**Issue by tacaswell** [NSLS-II/bluesky#69]
e.g., {'all': func, 'event': func}

moved from https://github.com/Nikea/history/issues/3

**Comment by danielballan** [comment]
Duplicates are ignored by the CallbackRegistry. It looks like that happens [here](https://github.com/NSLS-II/bluesky/blob/master/bluesky/utils.py#L88).

All these cases produced no duplicate output:

```python
RE(plan, {'event': cb, 'all': cb})
RE(plan, {'event': [cb, cb], 'all': cb})
RE(plan, {'event': cb, 'all': [cb, cb]})
RE(plan, {'all': [cb, cb, cb]})
RE(plan, {'event': [cb, cb, cb]})
```
