### ISSUE TITLE
Revisit bluesky.examples

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#692]
Carrying over from discussion in #678, I think we actually agree about what is good and bad about `bluesky.examples` but are giving different weight:

Good things about `bluesky.examples`:

* It's easy to specify simple simulated detectors and motors succinctly.
* It is used pervasively in documentation and example notebooks.

Bad things about `bluesky.examples`:

* It does not perfectly match the ophyd Device and Signal API.
* More complex examples, involving monitoring or flying, reinvent a lot of ophyd in a half-baked way.

Let's start here: do we agree on these things?

**Comment by tacaswell** [comment]
From in-person discussions with @danielballan 

 - move the simulate device implementations to `ophyd.sim`
 - have teaching material depend on `ophyd.sim`
 - allow tests to depend on ophyd (likely with the import buried in a fixture so if we ever pull out `contraption` as a separate module it will be easy to change)

I'll take care of the tests, @danielballan will take care of the docs.

**Comment by danielballan** [comment]
@tacaswell summarized our plans in his comment above. Let me expand on them. We originally created the `bluesky.examples` module to give bluesky some "hardware" to test against. This was in early days when bluesky and ophyd development were not well coordinated at NSLS-II. In time, the objects in `bluesky.examples` became useful for teaching purposes as well and accidentally outgrew their intended role. We are, for the first time, revisiting the APIs in advance of the 1.0 release.

Problems with `Reader` and `Mover` in `bluesky.examples`:

* It confuses new learners that these (synthetic) hardware abstractions come from a module in _bluesky_, when they have just been told that hardware abstractions belong to _ophyd_.
* `Mover` _seems_ like it supports multi-axis devices (the documentation suggests so) but in fact it doesn't really.
* `Reader` provides a way to hack together a Device-like object with multiple fields, but its API does not resemble the API of `ophyd.Device`, the one that users would have to use to talk to _actual_ hardware. Therefore, its usefulness as a teaching tool is questionable.

To address these problems, we are:

* moving synthetic hardware instances (like `det` and `motor`) from `bluesky.examples` to `ophyd.sim` (as Tom noted above). To avoid breaking a ton of example code outright, `bluesky.examples` will contain a shim import with a user-friendly warning or error, as needed.
* replacing `Reader` with `SynSignal` + `Device`, which reuse actual ophyd code and generate more helpful/realistic simulated devices -- rather than giving users yet another API to learn
* replacing `Mover` with `SynAxis`, again a more realistic movable device

One benefit of stuffing synthetic "hardware" objects in `bluesky.examples` was that users could experiment with bluesky without installing pyepics or EPICS. With this in mind, we will make it possible to install ophyd without pyepics or EPICS; therefore, users can continue to play with synthetic hardware before installing any heavy non-pure-Python dependencies. This was already on our roadmap, since we want ophyd to play well with other communications libs such as pyCA and caproto.

**Comment by teddyrendahl** [comment]
Just saw this. Very much like the idea. 

At SLAC, we also have a separate `sim` directory that holds simulated devices for us. We also took your idea for `using_fake_epics_pv` and modified it a little. Now it simply takes what it is given and runs the appropriate callbacks. There is a little work to do (if you put to your `write_pv`, the `read_pv` should probably be updated e.t.c), but the concept has been useful. Right now, we are largely using it to run unittests on all our ophyd devices. For example, 

```python

@using_fake_epics_pv
def test_device_remove(dev):
       dev.remove()
       assert dev.remove_sig._write_pv.get() == 1
```
I think it is a cool concept. Especially if it is flushed out enough that you could quickly simulate any Ophyd device for use in simulations e.t.c. Probably out of scope for the issue above, but wanted to make sure it was on your radar.

**Comment by danielballan** [comment]
That does seem useful! Sort of like an EPICS-specific mock object. Thanks for putting it on our radar. Let's work together to flesh that out more post-1.0.
