### ISSUE TITLE
When state is paused, raise RuntimeError from None

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#704]
A good suggested made in an APS tutorial

**Comment by tacaswell** [comment]
This is a bit too cryptic for me....

**Comment by danielballan** [comment]
Haha, sorry, I literally created this issue on a projector in the middle of a tutorial. It's easier to write the PR than explain here. Stand by....

**Comment by danielballan** [comment]
OK, I misunderstood the purpose of [PEP 409](https://www.python.org/dev/peps/pep-0409/) so I actually don't have a solution in mind here. Let me explain the problem.

It struck one developer at the APS tutorial that it's inconsistent that Ctrl+C causes the RunEngine to print but not raise, whereas attempting to invoke `__call__` while the RunEngine is in a paused state raises. This seems like a fair criticism.

I wonder if, when the RunEngine pauses, it's possible to make it raise a proper exception but only show a terse message, not a full traceback. That would (1) be consistent, (2) allow us to remove `raise_if_interrupted`, (3) continue to avoid throwing a long traceback in a users' faces when they pause.

There are hooks in the language to do this kind of thing, but we should only touch them if we are certain we put things back to normal when we're done and not cause bad side-effects.

**Comment by tacaswell** [comment]
I am not sure I agree there is an inconsistency here.  In the case of `ctrl-C` we are hi-jacking the signal handling to cleanly pause the RE (we need to absract that signal handling out, but that is a different issue) so it should not raise (as there is nothing we want to let people catch).

On the other hand, failing at `__call__` is exceptional behavior (but given the current system we also don't want people catching, but that is neither here-nor-there).

Don't we already have a `raise_if_interupted` that does this?

**Comment by danielballan** [comment]
"There is nothing we want to let people catch," is a good point, but the existence of `raise_if_interrupted` is evidence that using an Exception often makes sense here. I think the only reason we are printing instead of raising is for a more readable display. If we could get the readable display _and_ always raise a proper Exception, I think that would be better.

**Comment by tacaswell** [comment]
but we have that because people are using it _wrong_ ;)
