### ISSUE TITLE
Revisit plan_tools

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#721]
The module `bluesky.plan_tools` contains `print_summary` and `plot_raster_path`. We were never really happy with the name (what's a "plan tool"?).

We should think of this module as a group of functions that *comsume* plans -- RunEngine stand-ins -- with the promise that nothing in this module actually touches hardware. They are allowed to access `.name`, `.root`, `.parent`, and `.describe()`, but not `.read()` or above all `.set()`. The name `bluesky.sims` for "simulators" seems reasonable. We can shim `bluesky.plan_tools` as an alias for awhile to avoid an API break.

Thoughts?

**Comment by stuartcampbell** [comment]
Why not just leave `simulators` as you can always shorten it or squash it on import ?

**Comment by prjemian** [comment]
While you are at it, `print_summary` is a very broad name for something that is limited to plans.  Less concerned that the module is named `plan_tools`.  That name actually helps identify that `print_summary` is limited to only plans.

**Comment by danielballan** [comment]
That's valid about `print_summary`. Suggestions for better names? `summarize_plan`?

**Comment by danielballan** [comment]
Other names for proposed (not yet written) members of `bluesky.simulators`:

* `est_time`
* `check_limits`
* `check_connections`

**Comment by stuartcampbell** [comment]
`print_plan_summary` ?

**Comment by prjemian** [comment]
either `summarize_plan` or `print_plan_summary are fine, the latter is easier to find in an alphabetized list since it starts with the verb

**Comment by danielballan** [comment]
I like that metric and I'll remember it (i.e., start the name with the most descriptive word -- usually the verb). But "summarize" is a verb too! :-D

**Comment by danielballan** [comment]
Pushing toward a conclusion on this -- I'm surprised that people want `plan` in the name, but I'm aware that maybe I'm just to used to the idea of these have normal opinions. I would have gone with:

* `bluesky.simulators.summarize`
* `bluesky.simulators.check_limits`
* `bluesky.simulators.check_connections`
* `bluesky.simulators.est_time`

@prjemian Would you advocate for appending `_plan` to some or all of the above?
