### ISSUE TITLE
Create 0.10 tag/release

### ISSUE THREAD

**Issue by stuartcampbell** [NSLS-II/bluesky#724]
This is really just an issue to communicate that we are intending the tag the next release shortly so we can start rolling it out during the NSLS-II August shutdown.

We should decide on a different communication forum/platform for this type of thing as the project grows outside of Brookhaven.

**Comment by prjemian** [comment]
Perhaps gitter.im ?

**Comment by danielballan** [comment]
@prjemian We have started using https://gitter.im/NSLS-II/DAMA. Some non-branded gitter.im room would be fine too. Do you have any set up already?
