### ISSUE TITLE
Message validation

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#73]
Various docstrings and docs claim that certain messages and message sequences are not allowed. We don't actually validate all of them yet, so the RunEngine is likely to fail in nasty ways if users break the rules.

A running list of things to validate:

- [x] 'checkpoint' must not come between 'create' and 'save
- [ ] 'subscribe' cannot subscribe to 'start'
- [ ] 'save' must follow 'create'
- [ ] 'deconfigure' must follow a 'configure' with the same target

**Comment by danielballan** [comment]
(For the record, as @ericdill knows from offline conversations, we now do allow 'subscribe' to start.)

**Comment by danielballan** [comment]
@ericdill If you are interested in revisiting this, here's one way it could be done with surer accuracy and less repeated logic and code:

Use `RE.unregister_command` to remove some of the built-in methods and replace that with mocked-up alternatives methods that don't actually do anything. The internal logic of RunEngine itself -- both the state machine and the numerous flags -- will be exercised. They won't need to be mocked up separately. The mocked-up methods can watch for things like `IllegalMessageSequence`.

**Comment by tacaswell** [comment]
Closing this as we have many validation checks in place.
