### ISSUE TITLE
Rename mv -> mov to avoid ambiguity with UNIX mv

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#732]
Between ophyd and bluesky, we are internally inconsistent about using `mv` and `mov` to mean "move". In Slack, @tacaswell, @stuartcampbell, and I are voting for switching to `mov` across the board to avoid ambiguity with UNIX `mv`.

This means:
* A new `mov` plan will be added as a synonym for `mv`.
* The `mv` plan will issue warnings for at least one release before we remove it.
* The new `mvr` plan will be renamed `movr`. It hasn't been released yet, so this is a painless change.
* The new magics, `%mov` and `%movr`, can stay named as is.

It's not too late for others to offer other views!

**Comment by stuwilkins** [comment]
I wonder if it would be a good idea to somewhere (here?) list all these magic/commands and see if we can make them all consistent. Does this make sense?

**Comment by stuartcampbell** [comment]
I vote 👍 for consistency! 😄

**Comment by danielballan** [comment]
@stuwilkins By all means.

**Comment by stuwilkins** [comment]
Should we then come up with a command list? This would be a good opportunity to also see if there are commands missing and some which are no longer needed. Perhaps also looking at what people have generated themselves in their own profile would be informative?

**Comment by danielballan** [comment]
Relevant:
* [ophyd release notes in progress, going through commands.py members](https://github.com/danielballan/ophyd/blob/1c9ecc96501b5b1c0dce0dab0920004ac57ac224/doc/source/release_notes.rst#070)
* [documentation in progress, listing new magics](https://github.com/danielballan/bluesky/blob/3cab61fa830d6e7d3c8ee1c041f010aafd43d2d0/doc/source/magics.rst#built-in-magics)

**Comment by danielballan** [comment]
I have mixed feeling about this. Abbreviate "move" as "mov" is like abbreviating "June" as "Jun". It hardly feels worth it. Can we punt this to the next release and discuss it as part of #740?

**Comment by danielballan** [comment]
`mv -> move` and `mvr` -> `rmove` have been suggested. We might also adopt that pattern more generally: `rscan`, etc.

**Comment by danielballan** [comment]
How about this:

* `plans.mv` and `plans.mov` are synonyms
* likewise for `plans.mvr` and `plans.movr`
* Leave the magics as `%mov` and `%movr`

@stuartcampbell and I are happy with this.
