### ISSUE TITLE
"DiagnosticPreprocessor"?

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#736]
Pulling out a comment from @tacaswell's review of #720:

> 🚲 🏘 'diagnostic preprocessor' sounds like a tool you reach for when things are broken, not day-to-day operations.
housekeeping
standard
background
bookkeeping
moosefish
actuarial
status
health
checkup
tuneup

Sure, it would be painless to change because it hasn't been released yet. I'm not particularly fond of "DiagnosticPreprocessor" but none of these suggestions jump out at me either. Tom, if I'm remembering right, you originally defended this name because these readings are often used for QA / sanity checks.

**Comment by danielballan** [comment]
@tacaswell and I are both happy with the name `Background`. I'll pull the trigger on this tomorrow unless anyone objects, to get the name in place before we release. This seems reasonably readable to me:

```python
from bluesky import Background
bg = Background()
RE.preprocessors.append(bg)
bg.monitors = []
```

**Comment by stuartcampbell** [comment]
Seems fine to me.  Is it worth informally polling a couple of beamline folks ?

**Comment by danielballan** [comment]
Good idea, @stuartcampbell. I sent an email.

**Comment by danielballan** [comment]
There is consensus that the name 'Background' is problematic. E.g.:

> Background is a reserve word for our world utilized many places for all the detectors or monitors.

Alternative suggestions I have received so far:

* SamMemo ("sample memo")
* Com_mon ("common monitors")

This feature is not really sample-related, so I worry that SamMemo is misleading. But I think we could work with "common": this object specifies measurements _common_ to all plans executed by this RunEngine.

Maybe:

```python
from bluesky import Common
common = Common()
common.monitors.append(det1)
common.baseline.append(det2)
```

Is `Common` to general of a name? I think `common.monitors` and `common.baseline` work nicely.

**Comment by prjemian** [comment]
Can you describe, in a few simple terms, what exactly this should do?  A
clear name should emerge from that process.  The proposed names do not help
me to use this.

**Comment by danielballan** [comment]
Good suggestion.

The new feature is documented in [this section](https://nsls-ii.github.io/bluesky/plans.html#diagnostic-preprocessor) under that provisional name `DiagnosticPreprocessor`, which I think we generally agree does not help people understand what it is _for_.

Briefly, the object provides users with a simple way to (1) take baseline readings before and after each run, (2) monitor extra signals during a run, (3) "fly" flyable devices during a run.

To explain the implementation and the motivation a bit more: The object is a plan preprocessor -- a plan that takes in other plans and modifies them. Currently, using plan preprocessors involves messing with nested generators. These are powerful, and they feel like a correct low-level abstraction for this feature, but they are neither simple to explain nor convenient to use interactively. This new object is a plan preprocessor _with state_, enabling users to easily make changes in one place that affect all plans they will execute, which seems to be the most common usage.

**Comment by prjemian** [comment]
with no imagination whatsoever (and strong influence from names in the Java world): `PlanPreprocessorWithState`
It's bulky but direct.

**Comment by tacaswell** [comment]
That is too generic, this is applying a specific set of pre-processors (each of which are available as either a `*_wrapper` or `*_decorator` already) to every plan that goes through the RE.

We need a name that makes your typical beam line scientist think of:

> Briefly, the object provides users with a simple way to (1) take baseline readings before and after each run, (2) monitor extra signals during a run, (3) "fly" flyable devices during a run.

**Comment by prjemian** [comment]
more like this?  `PreprocessorSupplementalData` or `SetupSupplementalData`

**Comment by tacaswell** [comment]
I like `SupplementalData`!

**Comment by prjemian** [comment]
worksforme

**Comment by stuwilkins** [comment]
FWIW I really like `SupplementalData` also!
