### ISSUE TITLE
Plan names are too long

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#740]
We have received feedback that it would be nice to provide shorter names for plans like `relative_outer_product_scan`. I think we should consider changing the names we document and teach. There is no reason we can't support aliases for the existing names indefinitely, so this would not break user code.

Some ideas:

count (fine as is)
scan (fine)
relative_scan -> rel_scan
inner_product_scan -> joint_scan
outer_product_scan -> grid_scan

cc @stuwilkins

**Comment by danielballan** [comment]
@stuwilkins This isn't exactly what you were asking about, but it grew out of a conversation that you initiated. Are you against / in favor of / ambivalent about shortening the advertised names as above? To reiterate, the original names would still work, but the documented ones would make a better impression, be more intuitive and succinct.

Separately, we can still work on a set of standard import-time abbreviations (ct, asc, etc.) but I think that's an nsls2tools issue.

**Comment by ambarb** [comment]
Something to maybe also consider is the likelihood of a user to use "scan" as a variable and overwrite the function.  Is this just a learning exercise for the user (especially if aliases are adopted by the user who does not know the base function of `scan()`) or is it better to remove the ambiguity (like mv vs mov)?

@danielballan When you say nsls2tools issue, do you mean specific to the facility or specific to a beamline?

**Comment by prjemian** [comment]
Not necessary (IMO) to make newer names.  I like descriptive names. 
They should be terse , yet descriptive and unique.  Can always use 
alternatives in Python, such as:

```
import bluesky.plans as bp
# ...
bp.scan()
```

**Comment by stuwilkins** [comment]
Hi @danielballan Thanks, I think that I agree with @prjemian that they should be terse and descriptive. I also think the description should be intuitive so I prefer `grid_scan` to `outer_product_scan` personally. 

My concern was that with very long names they won't get used and the tendency will be for everyone to alias them. If this is done in a standard way (such as in nsls-ii-tools) then that is great, if done on a per beamline basis that can get confusing when staff move between beamlines. We are already seeing this on the soft x-ray beamlines with `mono` vs. `pgm` etc.

**Comment by stuartcampbell** [comment]
I agree I like @danielballan 's new shorter names.  I don't see a problem in changing the defaults and then we can keep the old names so they keep working as well.
