### ISSUE TITLE
Clean private method on callbacks?

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/bluesky#751]
Some callbacks need to clean themselves so that they can operate on the next header.
Can we:
1. Add a class variable to `CallbackBase` which will be overwritten, which contains a dict: `{variable_to_be_cleaned: default_value}`
1. Add a `_clean` method onto CallbackBase which:
```python
for attr, dv in self.clean_dict.items():
    setattr(self, dv)
```

**Comment by tacaswell** [comment]
:-1: This should be taken care of in the handling of the `'start'` document.

**Comment by CJ-Wright** [comment]
hmm ok

**Comment by tacaswell** [comment]
There is a balance between 'frameworks make things easier by doing the boring stuff' and 'frameworks make things harder by having to understand them to do something quite simple'.  This seems on the side of adding more complexity than it is taking away boring things.

**Comment by prjemian** [comment]
Shouldn't any cleanup belong in the handler for stop documents?

**Comment by tacaswell** [comment]
It can be handy for de-bugging to leave the cleanup to when you start processing the next start document (that way the state of the last run is accessible to you after `RE` returns).

**Comment by danielballan** [comment]
FWIW I usually do the cleanup in the stop documents myself, but I think you can make a fair case either way.

**Comment by danielballan** [comment]
Conclusion: it can make sense to cleanup on stop or manually -- to taste -- and we won't enforce a convention on the base class.
