### ISSUE TITLE
Change %ct magic and remove other magics

### ISSUE THREAD

**Issue by stuartcampbell** [NSLS-II/bluesky#756]
Change `%ct` to use a private RunEngine that does not subscribe to the databroker. 

The golden rule is that magics do not write data that will be kept.

We should therefore also remove the magics that are doing real data collection.

**Comment by prjemian** [comment]
:-1:  the golden rule seems more sneaky, users may do otherwise

Perhaps consider that "supplied magics do not ..."

**Comment by stuartcampbell** [comment]
Fair enough, I agree that we can just say that our supplied ones don't save data.  This was more of an issue just capturing a conversation we were having with @stuwilkins @ambarb

**Comment by danielballan** [comment]
FYI, I had not caught up on this conversation when I posted #760.Anyway, I agree that users can do whatever they like and we shouldn't misdirect them about what is possible. I think we feel more comfortable with #760 because it avoids _providing_ tools that we know to be problematic.
