### ISSUE TITLE
List subscriptions on the RunEngine

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/bluesky#779]
Would it be possible to list subscriptions on the RunEngine?
It seems that the only way to unsubscribe something is to know it's token. However, unless this is actively saved into memory somewhere this is currently unknowable.

## Expected Behavior
```python
>>> print(RE.list_subs())
{0:' db.insert,'
1: 'confirm_saved',
2: 'ZMQ'
...
}
```
If this is already possible, it isn't documented in the Live Visualization section with the other subscription things.

**Comment by danielballan** [comment]
There is no way to provide a view quite as simple as that which is also correct in the general case. I do not think we will exposure a public way to do this.

You can get `RunEngine.dispatcher.cb_registry.callbacks` but because of considerations related to garbage collection, there is a layer of indirection that makes the reprs less than informative:

```python
In [3]: RE = RunEngine()

In [4]: def f(name, doc):
   ...:     return None
   ...:

In [5]: RE.subscribe(f)
Out[5]: 0

In [6]: RE.dispatcher.cb_registry
Out[6]: <bluesky.utils.CallbackRegistry at 0x11967a898>

In [7]: RE.dispatcher.cb_registry.callbacks
Out[7]:
{<DocumentNames.stop: 'stop'>: {1: <bluesky.utils._BoundMethodProxy at 0x119698358>},
 <DocumentNames.start: 'start'>: {2: <bluesky.utils._BoundMethodProxy at 0x119698630>},
 <DocumentNames.descriptor: 'descriptor'>: {3: <bluesky.utils._BoundMethodProxy at 0x119698828>},
 <DocumentNames.event: 'event'>: {4: <bluesky.utils._BoundMethodProxy at 0x1196989e8>},
 <DocumentNames.bulk_events: 'bulk_events'>: {5: <bluesky.utils._BoundMethodProxy at 0x119698940>}}
```

**Comment by tacaswell** [comment]
I am :-1: on adding public API for this.  I also would not suggest digging into the dispatcher like that.

The reason we return the token is so that you can remove it later.

**Comment by CJ-Wright** [comment]
Yes but many times the token is not put anywhere so it is lost. Eg it is in the ipython profile and not placed into a variable.

**Comment by tacaswell** [comment]
The `BEC` and `db.insert` registrations are intentionally hard to remove.  There is an edge between library development (bluesky) and application development (what is effectively being done in the profiles).

If you just want to turn the BEC off, use the methods on it to disable plotting / printing.

**Comment by CJ-Wright** [comment]
Actually I was looking to turn off `db.insert` to not flood the databroker with zeros (since we will be testing out live analysis without beam initially). But I guess I could just comment them out.

**Comment by tacaswell** [comment]
:+1: to just commenting them out for testing (or setting using a temporary databroker)

**Comment by CJ-Wright** [comment]
Cool.
