### ISSUE TITLE
DOC: document hints

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/bluesky#782]
Hints seem helpful for all sorts of callbacks. Would it be possible to get some docs on what to expect in terms of keys and values?

**Comment by danielballan** [comment]
There are currently only two kinds of hint, documented [here](https://nsls-ii.github.io/bluesky/callbacks.html#hints). The naming was borrowed for xarray, which has similar concepts.

As the warning in the documentation indicates, this is an experimental feature. We will fearlessly break this API in the future as we learn more about how to make these useful. If you decide to rely on them, be advised that you are taking on extra maintenance work in the future.
