### ISSUE TITLE
progress bar fails on pseudo positioners

### ISSUE THREAD

**Issue by tacaswell** [NSLS-II/bluesky#794]
can not subtract the two position values.

**Comment by ambarb** [comment]
@tcaswell. Are these psedomotors with epics motor records or like the sy and sz at CSX1? Those are currently epics calculation records.

**Comment by tacaswell** [comment]
This is for python-level pseudo positioners which report their position as a tuple sub-class (for example the tardis).  Anything done at the epics level is exposed to ophyd as a motor and should work correctly.

**Comment by danielballan** [comment]
Closed by #810 and NSLS-II/ophyd#438
