### ISSUE TITLE
MPL callbacks fail to update when subscribed to zmq

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/bluesky#795]
When using ZMQ, subscribing MPL based callbacks to the `RemoteDispatcher` causes them to not be updated.

## Expected Behavior
MPL based callbacks update themselves when the ZMQ feed it idle.

## Current Behavior
MPL based callbacks don't update themselves when running inside ZMQ

## Possible Solution
It seems that ZMQ's loop and MPL's `draw_idle` loop are in conflict, with MPL never getting control.

## Steps to Reproduce (for bugs)
1. start up proxy
1. Run
```python
# pull from local data, not needed at beamline
import matplotlib.pyplot as plt
import numpy as np

from bluesky.callbacks.broker import LiveImage
from bluesky.callbacks.zmq import RemoteDispatcher
from shed.event_streams import istar

a = LiveImage('pe1_image')

def put_in_queue(nd):
    if nd[0] == 'event':
        nd[1]['data']['pe1_image'] = np.asarray(nd[1]['data']['pe1_image'])
    a(*nd)
    plt.pause(.1)


disp = RemoteDispatcher('127.0.0.1:5568')
disp.subscribe(istar(put_in_queue))
print("REMOTE IS READY TO START")
disp.start()
```
3. Run
```python
import numpy as np

# pull from local data, not needed at beamline
from bluesky.callbacks.zmq import Publisher
from bluesky import RunEngine
from bluesky.examples import Reader
from bluesky.plans import count
RE = RunEngine({})
p = Publisher('127.0.0.1:5567', RE=RE)  # noqa

det = Reader('pe1_image', 
             {'pe1_image': lambda : np.random.random((10, 10))})

uid = RE(count([det]))
```
Note that at the end of this neither the side 1D plots nor the cross hairs work.

## Context
This is going to cause tons of problems at XPD when we try to live ZMQ driven visualization.

**Comment by tacaswell** [comment]
I think you just need to install the qt_kicker https://github.com/NSLS-II/bluesky/blob/master/bluesky/utils.py#L691

**Comment by tacaswell** [comment]
```python
import zmq.asyncio as zmq_asyncio
loop = zmq_asyncio.ZMQEventLoop()
install_qt_kicker(loop=loop)
disp = RemoteDispatcher('127.0.0.1:5568', loop=loop)
...
```

**Comment by CJ-Wright** [comment]
Awesome thank you! 
We might want to put a note of this in the docs with the ZMQ stuff since is seems like this is a likely problem to run into.

**Comment by danielballan** [comment]
A simpler suggestion:

```python
disp = RemoteDispatcher('127.0.0.1:5568')
install_qt_kicker(loop=disp.loop)
```

Arguably this is already documented [here](https://nsls-ii.github.io/bluesky/callbacks.html#aside-making-plots-update-live) but the detail about using the same `loop` as the `RemoteDispatcher` could throw people, so I'll add some docs.

**Comment by CJ-Wright** [comment]
Thank you!
