### ISSUE TITLE
Change axis range in live_mesh.

### ISSUE THREAD

**Issue by awalter-bnl** [NSLS-II/bluesky#800]
Is it possible to have Live mesh axis ranges start from range_min - step_size/2 and finish at range_max + step_size/2 . This ensures that the "squares" are centered on the value in every case, at present they are centered in the middle of the scan but not at the edges.

**Comment by tacaswell** [comment]
By 'live_mesh' here do you mean `LiveGrid` https://nsls-ii.github.io/bluesky/callbacks.html#livegrid-gridded-heat-map which gives you squares that I think can miss the right locations.  Did you create this callback or did it come out of BEC?

**Comment by awalter-bnl** [comment]
Hi Tom,
Yeah by live mesh I meant live grid, sorry about that. and yes it is through the BEC when specifying more than one plot channel (Z axis in this case).

cheers
Andrew


Andrew Walter
Assc. Scientist
NSLS II, Photon sciences directorate
Brookhaven National Laboratory
Building 741, Rm 108
Upton New York, USA, 11973
Email: awalter@bnl.gov<mailto:awalter@bnl.gov>
Phone:
office: 631 344 4055
        beamline: 631 374 1621



On Aug 31, 2017, at 8:50 PM, Thomas A Caswell <notifications@github.com<mailto:notifications@github.com>> wrote:


By 'live_mesh' here do you mean LiveGrid https://nsls-ii.github.io/bluesky/callbacks.html#livegrid-gridded-heat-map which gives you squares that I think can miss the right locations. Did you create this callback or did it come out of BEC?
