### ISSUE TITLE
ENH: base mpl callback class?

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/bluesky#814]
Would it be possible to make a base mpl callback class? It seems that many times some of the mpl things are common (eg make a figure if none provided) and it would help to have many of the mpl configuration things (fig size, fig title, etc) in one base class.
Thoughts?

**Comment by danielballan** [comment]
For me it's usually faster to redo this stuff than remember what a base class named things, but I guess it would depend on the details. Would you be willing to post a PR with the possibility that might decide not to merge it?

**Comment by tacaswell** [comment]
There are enough knobs on matplotlib and exactly how you want to set it up I am skeptical that a base class which has enough flexibility will actually be simpler and a simple base class will project out too much complexity to be generally useful.

**Comment by CJ-Wright** [comment]
Sure, I can put in a PR. Although I want to put in a PR without this first which allows the addition of titles and window names to the callbacks. Many of the callbacks look similar (live images especially) so knowing where the data came from or what kind of data that we're looking would be very helpful.

**Comment by tacaswell** [comment]
In terms of composability, it is probably better to move away from the LivePlot, LiveGrid, etc implicitly creating the figure / axes and instead having that passed in.  It is best to think of those as wrappers around a single `matplotlib.artist.Artist` that knows how to update it's self given a stream of documents.   Given that context, `LivePlot` has no business messing with axis labels, titles, etc.

Moving towards a model where one layer creates a bunch of the artist wrappers base on the contents of `Start` and sets up the figure / axes is probably the correct long term solution (BEC feels right).

**Comment by CJ-Wright** [comment]
I'm ok with this so long as I don't have to use BEC, since there is no real corollary on the analysis side.

**Comment by danielballan** [comment]
Definitely! BEC is an out-of-the-box solution. We definitely would encourage advanced users like you to go ahead an disregard it if you wish. Custom plans with explicit callbacks will always better more powerful -- with the tradeoff that they take more person-power to configure.

**Comment by CJ-Wright** [comment]
Cool
