### ISSUE TITLE
Best way to plot peak positions as a function of temperature

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/bluesky#817]
One of the Quantities of Interest (QOI) at XPD is peak position as a function of temperature (or some other 1D variable). I was wondering what the best way to do this would be. I can extract the peak positions with `argrelmax` from `scipy.signal`.

## Expected Behavior
Some sort of plot of peak position(s) vs. temperature.

**Comment by tacaswell** [comment]
This does not seem like a bluesky question.

There are a great number of ways to find (single?) peaks in a curve, which one is best depends both on how you tune the parameters, exactly what it looks like, and how much physics you can bake in.

**Comment by CJ-Wright** [comment]
I'm not worried about the peak extraction, I'm just asking which callback is appropriate for plotting.
