### ISSUE TITLE
wrong syntax in documented example for suspenders

### ISSUE THREAD

**Issue by awalter-bnl** [NSLS-II/bluesky#818]
In the the documentation for suspenders the example indicates that the line to define the suspender should be:       sus = SuspendFloor(beam_current, 2, 3)

In reality it should be: sus = SuspendFloor(beam_current, 2, resume_thresh=3)

as resume_thresh is an optional input. It took me a while to work this out when trying to set up suspenders.

**Comment by danielballan** [comment]
@awalter-bnl, thanks for your report and your saintly patience. I have submitted a fix.
