### ISSUE TITLE
Audit dependencies

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#823]
These are the required dependencies in the requirements.txt.

```
cycler
event-model
historydict
jsonschema
matplotlib
numpy
super_state_machine
toolz
tqdm
```

We have discussed removing our dependency `super_state_machine` in favor of a hand-rolled solution since we aren't using much of its capability. It's a clever library but not a commonly-used one, and it could become a fragile dependency.

We might also make matplotlib optional. I recall that our original reasoning for making it a hard dependency was that experimental science almost always requires some visualization. But on the other hand, bluesky might be run on systems without display. Matplotlib brings in heavy dependencies and significant import time.

All the rest of the requirements are light and pure Python -- with the exception of numpy which is obviously needed. They are either from the NSLS-II org (historydict, event-model) or commonly used and likely to be well-supported in the future.

**Comment by CJ-Wright** [comment]
If matplotlib is going to be optional what is the plan for callbacks? Will there by a try/except import?

**Comment by danielballan** [comment]
Something like that. I dislike it when packages force me to discover optional dependencies in that way, but I'm starting to think its the lesser evil in this case.

**Comment by CJ-Wright** [comment]
I like the separation of MPL. One could imagine separating the visualization from the data acquisition completely via ZMQ and friends. One could even imagine having a server blade run your experiment while visualizing it from the comfort of your very own office, which would make the MPL dep superfluous.

**Comment by ordirules** [comment]
I agree. Try/except is a good thing to add, and requires little effort. Looks like all the imports are mostly in callbacks/ which is good. This might help contain them for machines that don't need plotting.

About potentially replacing matplotlib in bluesky (in case it was considered), I would disagree. Matplotlib is a great library in that it supports multiple backends and works out of the box most of the time. I'm not sure if it is worth the extra effort of extending the built in callbacks to support other plotting libs (but of course external use is encouraged). I'd say definitely remove the dependency, but let the usage of other plotting libs be up to the user? If one has a good solution in the long run, it can then be considered to add?

**Comment by ordirules** [comment]
since we're discussing dependencies, `LiveImage` also has an `xray_vision` dependency:
```        from xray_vision.backend.mpl.cross_section_2d import CrossSection```

might be a good idea to see if there is an alternative to this as well.

**Comment by danielballan** [comment]
Yeah, it might be worth vendoring that (which is what we do in databroker-browser).

**Comment by danielballan** [comment]
...Or maybe working on a separate library of image viewing utilities. Image viewing (beyond simple `imshow` might be across the threshold of what we want to ship in bluesky itself, given complexity and heavy dependencies.

**Comment by CJ-Wright** [comment]
Xray vision may need a bit of a refactor at the least.

**Comment by danielballan** [comment]
I created two actionable issues from this discussion. Closing.
