### ISSUE TITLE
Ship 'unboxed' versions of plans that do not create runs.

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#833]
If a user wants to combine several plans into a custom plan but save the resultant data as part of a single 'run' (i.e., getting one scan ID), they cannot easily reuse the built-in plans. The built-in plans are create one run per invocation.

Two possiblities:

* Create a counterpart for each plan, like `unboxed_count` for `count` and `unboxed_scan` for `scan`.
* Add a keyword argument like `unboxed` for all plans.

(Do we already have an issue for this? We've been aware of the issue for awhile, but I couldn't find an open issue on GH.)

**Comment by tacaswell** [comment]
I like option 1 much more than option 2

**Comment by danielballan** [comment]
I start with this:

```python
import bluesky.plans as bp

def custom_scan(...):
    yield from bp.scan(...)
    yield from bp.scan(...)
```

"Oh darn that made two runs and I wanted to jump that data into one run to make my analysis easier." Honestly, neither of these look great:

Option 1:

```python
import bluesky.unboxed_plans as bup
import bluesky.plans as bp

def custom_scan(...):
    # create md similar to how we do in the source of bp.scan
    @bp.run_decorator(md=md)
    def inner():
        yield from bup.scan(...)
        yield from bup.scan(...)
   uid = yield from inner()
   return uid
```

Option 2:

```python
import bluesky.plans as bp

def custom_scan(...):
    # create md similar to how we do in the source of bp.scan
    @bp.run_decorator(md=md)
    def inner():
        yield from bp.scan(..., unboxed=True)
        yield from bp.scan(..., unboxed=True)
   uid = yield from inner()
   return uid
```

**Comment by danielballan** [comment]
@stuartcampbell had a wild idea: a variant of `pchain` that uses plan_mutator to rip off the open_run/close_run messages. I kind of like that.

**Comment by tacaswell** [comment]
I think ripping out the start/stop messages will cause issues because the plans will not get back the expected results (the uid from the start).  I think we do not do anything other than return the uid, but I have definitely written plans for beamlines that do so.  Can see work arounds to my immediate concerns, but worry it will quickly grow more complex than we want to deal with.

**Comment by danielballan** [comment]
Given the complexity of employing an "unboxed" plan (illustrated above) it's probably better _not_ to provide this intermediate layer. It will be easier for users to use `trigger_and_read` and `mv` directly.
