### ISSUE TITLE
Plot initial guess in LiveFitPlot

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#841]
A common problem with LiveFit is a poor initial guess. It would be convenient if LiveFitPlot displayed the initial guess (say, as a gray line) on the same axes as it currently displays the best fit.

Any interest in taking this one, @licode?

**Comment by licode** [comment]
Sounds good. I will work on this.

**Comment by licode** [comment]
close by https://github.com/NSLS-II/bluesky/pull/859
