### ISSUE TITLE
Make matplotlib an optional dependency

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#842]
See discussion in #823, where this was the consensus. This requires making it a class-level import in bluesky/callbacks/core.py and potentially elsewhere.

**Comment by danielballan** [comment]
@teddyrendahl Speaking of your suggestion to break up `callbacks/core.py`, how would you like to see that done? How about:

* table.py
* fitting.py
* matplotlib.py  # rather than 'plotting.py', to make room for other plotting frameworks
* core.py  # base classes

**Comment by teddyrendahl** [comment]
Yeah, to be honest, hadn't thought about it a ton after my original complaint 😝 

Seems reasonable. `matplotlib.py` seems kind of awkward but I see the problem you are trying to avoid.

**Comment by danielballan** [comment]
Yeah I have fixed feeling about naming like that. On the one hand, I trust in namespaces and `bluesky.callbacks.matplotlib` is very clear. It avoids inventing new names. On the other hand, it can be very confusing to humans, especially beginners. Maybe `bluesky.callbacks.mpl_plotting` would be safer?

**Comment by danielballan** [comment]
All of these are going to get bulk-imported into `bluesky/callbacks/__init__.py` (if the dependencies are available) for back-compat and to avoid hard-to-remember imports, so this naming choice mainly affects devs.

**Comment by teddyrendahl** [comment]
`mpl_plotting` sounds cleaner, but I'm bad with names. After all I'm the reason you have a function called `stub_wrapper` in your library now ...

**Comment by danielballan** [comment]
That Teddy, man, he can be a real stub wrapper sometimes.

**Comment by prjemian** [comment]
think of this case
```
from bluesky.callbacks import matplotlib 
```
perhaps `bluesky.callbacks.mpl_plotting ` avoids the support requests

**Comment by danielballan** [comment]
Yeah. Amen to avoiding that support request.

**Comment by danielballan** [comment]
Worst of all, in Tom's case, who knows whether it would show up as a bluesky issue or a matplotlib issue!

**Comment by hhslepicka** [comment]
👍 to `mpl_plotting`
