### ISSUE TITLE
Tiny command to check if proxy is running/in a good state

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/bluesky#846]
It would be nice to have a command that checked if the proxy for zmq was running. If it isn't running problems ensue and it isn't always easy for the users to check all the terminals to find the proxy one.

## Expected Behavior
Run command, terminal says if there is a proxy running in good standing or not.

## Current Behavior
Proxy may or may not be running and the users/beamline staff have no idea.

## Context
This causes us a bunch of grief with the automated pipeline which relies on the zmq proxy to run to visualize and save users data.

**Comment by danielballan** [comment]
I don't think this is in scope for bluesky because it would have to make some assumptions about the configuration of the proxy (or else be very brittle). I suggest you implement something in xpdacq.

**Comment by danielballan** [comment]
Let me expand on that answer a bit. Here's one way you can check whether the proxy _may be_ already running:

```
# Start the proxy.
$ bluesky-0mq-proxy 5577 5578
Loading...
Connecting...
Receiving on port 5577; publishing to port 5578.
Use Ctrl+C to exit.
```

```
# In a separate terminal, try starting it again
$ bluesky-0mq-proxy 5577 5578
Loading...
Connecting...
Traceback (most recent call last):
  File "/Users/dallan/miniconda3/envs/dd/bin/bluesky-0mq-proxy", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/dallan/Documents/Repos/bluesky/scripts/bluesky-0MQ-proxy", line 19, in <module>
    proxy = Proxy(in_port, out_port)
  File "/Users/dallan/Documents/Repos/bluesky/bluesky/callbacks/zmq.py", line 126, in __init__
    frontend.bind("tcp://*:%d" % in_port)
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5653)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:10014)
zmq.error.ZMQError: Address already in use
```

Perhaps for XPD you may want to wrap that command in a bash script that hard-codes certain ports that you always plan to use and fails with a more informative message. At the library level, we can't do something like that because we can't assert that certain ports are free or even that users would only ever want to run one of these at a time.

**Comment by CJ-Wright** [comment]
Thank you!
I guess I could just write in the docs something to the effect of "always run the proxy command and if it fails you already had one running and are fine, and if it doesn't fail then you didn't have one running and now you do and are thus also fine."
