### ISSUE TITLE
[ENH] Consider make start.motors  None or [] for count()

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/bluesky#866]
I am asking for this because it makes exception handling really easy.  There is no need for an exception as long as there is something in the field.  Otherwise, I have to make things really complicated if I don't want to `pass`.

Please comment on whether someone is willing to give us a way around this.

**Comment by danielballan** [comment]
I gather you have some code like:

```python
motors = header['motors']
```

and you might be working around it like:

```
try:
    motors = header['motors']
except KeyError:
    motors = []
```

That's a fine pattern (I wouldn't blink at it) but this might be nicer:

```python
motors = header.get('motors', [])  # defaults to [] if 'motors' isn't a key
```

Your suggestion of adding 'motors' to count does not scale well. In my opinion, we don't want to force every plan to carry around the union of all the other plans' metadata keys. The solution above lets our plan code be leaner and it works well on user-defined plans that might be missing some metadata.

**Comment by ambarb** [comment]
I see why you don't like my suggestion.  

I am happy to see the nicer example because that gives me a level of discrimination that i did not have.  I did not realize `get()` could do this. Thanks a bunch @danielballan .
