### ISSUE TITLE
inne_product_scan doesnt' plot correctly

### ISSUE THREAD

**Issue by bisogni** [NSLS-II/bluesky#867]
By running an 'inner_product_scan', the automatic plot pops out however no data get really plotted. The template looks more like the one of a 'mesh/outer_product_scan'...

@danielballan @tacaswell can we have a quick fix?

![gc_diag_diode_gc_diag_grid_m3_diag_diode_m3_diag_grid_vs_pgmslt_d_bot_pgmslt_d_top](https://user-images.githubusercontent.com/24460486/30558084-4f8a7728-9c7e-11e7-9fa8-6ae58f26ffac.png)

**Comment by ambarb** [comment]
@cmazzoli From our discussion about https://github.com/NSLS-II/bluesky/issues/868, maybe you have a point if inner_product_scan is still broken as @bisogni reported.  However, if DAMA makes scan_nd do as you ask for any 2D motor scan, then things like spiral scans will be broken in in the way that they plot.  @danielballan can you weigh in on this since i think  this has something to do with the _md exceptions related to hints?

**Comment by cmazzoli** [comment]
Hi Andi,
Thanks, now I understand better.
Personally I think that DAMA has all the capability of taking the challenge
and recognizing of a cycler provides a linear scan (diff on motors have
always the same sign) or it is intended to be a mesh (periodic inversion of
sign on both).
However if they fear that they cannot do it, then we will adapt ;)
Please note that as far as I understand currently the 2D scan-nd assumed as
a mesh is the exception compared to the rest. Am I wrong?
Thanks again.
Claudio

**Comment by ambarb** [comment]
Claudio,

Yes, that is my observation.  If you have more than 2 motors for `scan_nd` than bluesky will make separate line plots for each in the LivePlot window.

**Comment by ambarb** [comment]
In essence, you could hack a th2th scan as you did earlier with scan_nd and just also add gamma scan from 0 to 0  (or wherever it is that you have it).  Or you may be able to get away with use tardis.l  in `scan()`

**Comment by cmazzoli** [comment]
Yes, I got the same idea (extra motor, I would rather prefer a non
interfering one like eta for example but basically the idea is the same..).
However, I would rather prefer DAMA to correct the problem suitably, if
possible. Dan
@danallan, could you please let us know?
Thanks.
Claudio

**Comment by danielballan** [comment]
Marked for completion before "1.0", meaning we should have a fix within the next week and half.

**Comment by cmazzoli** [comment]
:thumbsup:

**Comment by cmazzoli** [comment]
BTW tried with 3 motors instead of 2, it doesn't seem to be working anyway :(

**Comment by ambarb** [comment]
Really?
Did you use scan_nd or inner product scan?

The custom fixed Q energy scan uses scan_nd and that works just fine.  Curious to know what the difference is?

**Comment by cmazzoli** [comment]
This is the thread of inner_prod, this is what I used:  thought that it was a relevant piece of info for the developers, maybe.
As you correctly report, I assumed the other one was working no problem sa I already used it in the past.. :)

**Comment by jrmlhermitte** [comment]
addressed with #917 can someone maybe test this if they have time? :-)

**Comment by tacaswell** [comment]
Just watch @ambarb test this.  It is enough better to close this issue (@ambarb will follow up with a discussion about how to better handle inner product scans in general).
