### ISSUE TITLE
[ENH] Add LivePlot line style cycler

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/bluesky#872]
The number of colors increased with the matplotlib version change.  However, we still run out of colors in a single plot.  It would be great to add a cycler for different lifestyles (solid, dashed, dot, etc).

**Comment by danielballan** [comment]
This can be done without any changes to LivePlot. See for example [this page of the matplotlib documentation](https://matplotlib.org/examples/color/color_cycle_demo.html) and let us know if you have any questions.

I'm going to close this issue as I don't think it's in scope for bluesky, but I'm happy to answer follow-up questions here. It may be useful to have this issue as a record in case this comes up again.

**Comment by ambarb** [comment]
@danielballan I understand how to do this in a notebook.  Are you saying that I can make a custom plan do this?  Or are you telling me that if I want to cycle the line style that I need to plot the data in an python notebook and implement a line style cycler?  I already know how to do the later. I was just asking for an enhancement so that when someone comes in after an overnight script, then can quickly make a decision based on the bsui LivePlot figure.

**Comment by danielballan** [comment]
I think this should work exactly the same in a notebook or interactively at the terminal. Is that the question?

**Comment by ambarb** [comment]
My request was to make the LivePlot do this without me having to type anything in the window.  Are you saying that I can do this if I create a custom plan?  Or are you saying that I should manually re-plot the data and ignore the bsui plot that occurs with any scan?

**Comment by danielballan** [comment]
You can change the default matplotlib color cycle to be one with more colors in it. I think that would solve your problem. LivePlot can't automatically do this for you because it will never know in advance how many lines you plan to put on the same axes, but it could just always use a color cycle with a large number of colors.

**Comment by ambarb** [comment]
OK that makes sense.  This would be in the matplotlib bashrc, or I could alternatively import matplotlib and set it up that way.  The second option was already done so we could have the grid displayed.  So I will try it that way.  Thanks for your patience

**Comment by danielballan** [comment]
Sure, no problem. Yes, the matplotlibrc is the place to change this.
