### ISSUE TITLE
Labels on LiveGrid plots are swapped.

### ISSUE THREAD

**Issue by awalter-bnl** [NSLS-II/bluesky#874]
I have noticed that the labels on live grid (not the scale) is swapped. such that the Y axis label is placed on the X axis and the X axis label is placed on the Y axis.

**Comment by danielballan** [comment]
Good catch. You are on a roll for catching detail-oriented bugs in bluesky!

**Comment by awalter-bnl** [comment]
no problem, I am guessing this is an easy fix

**Comment by tacaswell** [comment]
@awalter-bnl How are you calling `LiveGrid`? Looking at https://github.com/NSLS-II/bluesky/blob/3d2853c401ecf4642a72116890462abdc9309e16/bluesky/callbacks/core.py#L434-L444 I am not sure how they could be getting flipped.

Doing

```python
from bluesky.callbacks import LiveGrid
import matplotlib.pyplot as plt

lg = LiveGrid((10, 17), 'I', xlabel='XLABEL', ylabel='YLABEL')
plt.show()

```

![so](https://user-images.githubusercontent.com/199813/32077529-b7f2f0a4-ba71-11e7-930b-b9af55ce5601.png)

looks like it is behaving correctly to me.

**Comment by awalter-bnl** [comment]
@tacaswell using the best effort system when we run a scan_2D plan at ESM then the plot has the labels around the wrong way. It is highly reproducible (it has happened at least 10 times so far). So if you can’t reproduce the error perhaps you can stop by the beamline and I can show you.

**Comment by tacaswell** [comment]
ok, I have a fix, `outer_product_scan` was not putting in dimensions correctly.

In future bug reports please note if it is triggered via BEC or by you directly creating the callbacks.

**Comment by awalter-bnl** [comment]
No problem, I realize I should have included that !-)
