### ISSUE TITLE
LiveGrid: matrix population and axis labelling mismatch

### ISSUE THREAD

**Issue by cmazzoli** [NSLS-II/bluesky#881]
We called LiveGrid via a mesh running on 2 motors from negative to positve.
I re-made the exactly same scan but asking the 2 motors to invert their direction (scanning from pos to neg).
LiveGrid produces a correct image in the first case.
In the second case the image does not correspond to the axis along the vertical direction (taken the axis label as correct, which seems reasonable as it compares to the motor instant values, the image should have been flipped upside down).
I have a picture to show, I try to attach it here..

![missinginversionyaxis](https://user-images.githubusercontent.com/11068694/32079275-0eb96660-ba78-11e7-96db-10c7b836816b.png)

## Steps to Reproduce (for bugs)

1.
2.
3.

**Comment by danielballan** [comment]
@tacaswell Was this closed by #882?

**Comment by tacaswell** [comment]
No, this is issues with way we fill it the array which makes some assumptions about the order and the limits.

The x-axis is correctly flipped (the minimum is around -0.65) but the y-axis the labels are inverted, but the data is not.

**Comment by danielballan** [comment]
Am I correct that we still don't have a conclusive answer on this?

**Comment by danielballan** [comment]
I believe that was fixed in #951.
