### ISSUE TITLE
SupplementalData should do baseline before beginning monitoring

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#931]
Currently, we start monitoring and then take baseline readings. If the same signal happens to be in both lists, it seems safer to take the baseline reading first.

**Comment by prjemian** [comment]
I'm new at this.  What you describe here is the order I assumed *was* happening on reading the documentation.  *Baseline* is what happens before collection begins (and after it ends).  *Monitor* happens during collection.  This is an obvious correction.

**Comment by danielballan** [comment]
Agreed. It should have been this way in the first place. In practice it has probably had little effect (they happen one right after the other) but this is clearly the better order.
