### ISSUE TITLE
simplify user support for default `wa` command

### ISSUE THREAD

**Issue by prjemian** [NSLS-II/bluesky#972]
Beam line users like and expect a command that prints current motor positions.  This is the `wa` command.  Its default reports motors in the `BlueskyMagics.positioners` list (from `bluesky.magics`).

## Current Behavior
Users can append to this list with commands such as:

    import bluesky.magics
    BlueskyMagics.positioners.append(m1)    # add one at a time
    BlueskyMagics.positioners.append(m2)
    BlueskyMagics.positioners += [m3, m4]  # add more than one motor

## Expected Behavior

This is too much code to type for users.  It could be simpler.  Also, it is hard to see how `BlueskyMagics` is defined from that import.  

## Possible Solution

I propose adding a function in `bluesky.magics` that manages this list.  Here is a function used by the [APS tomography setup](https://github.com/APS-2BM-MIC/ipython-user2bmb/blob/master/profile_bluesky/startup/00-startup.py#L30):

    def append_wa_motor_list(*motorlist):
        """add motors to report in the `wa` command"""
        BlueskyMagics.positioners += motorlist

Also, there are [examples](https://github.com/APS-2BM-MIC/ipython-user2bmb/blob/master/profile_bluesky/startup/11-motors.py#L19) of how it is used.

For the user, this code looks simpler, there is only one function to call regardless of how many motors to add and it is obvious where the function was defined:

    from bluesky.magics import append_wa_motor_list
    append_wa_motor_list(m1)
    append_wa_motor_list(m2)
    append_wa_motor_list(m3, m4)

**Comment by danielballan** [comment]
Is part of the problem that `+=` is a little opaque to Python novices? There is also `extend`:

```python
BlueskyMagics.positioners.extend([m3, m4])
```

To be honest, I think I prefer pointing users toward `BlueskyMagics.positioners` directly. Would we also need `remove_from_wa_motor_list` and `show_wa_motor_list`? It seems more straightforward to me to interact with the list directly.

But, if you think `append_wa_motor_list` would help with adoption, I would merge a PR adding it. I might quibble with the name -- `positioner` or `pos` for short is nice because it applies to things that aren't motors, like temperature controllers.

**Comment by tacaswell** [comment]
Shouldn't most of this configuration be done in the start up files?

I am with @danielballan , the helper is not that much shorter (particularly once you take tab-complete into account) and less clear.  If you have novice users you are either asking them to memorize another beamline specific magic command or learn a little bit of basic python.  Those _seem_ about the same level of complexity to me but if they learn about `list.append` and `list.extend` they can re-use that else where in the future, whereas `append_wa_motor_list` is very site and application specific.

**Comment by prjemian** [comment]
It's a matter of taste.  We have different experience.

**Comment by danielballan** [comment]
Fair enough. I hope we didn't just steamroll you, @prjemian. I would still merge that PR if you feel strongly about it. :- )
