### ISSUE TITLE
Announcement: Upcoming release candidate for v1.2.0

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/bluesky#976]
I intend to tag v1.1.0rc1 over the weekend. There are two important but small fixes to be made first, and a major documentation overhaul to finish and merge, before v1.1.0.

This release contains mostly bug-fixes and a couple new small enhancements. There will be one deprecation but no breaking API changes.

**Comment by stuartcampbell** [comment]
@danielballan Do you mean v1.2.0rc ?

**Comment by danielballan** [comment]
Yes, thanks. I have updated the issue title accordingly. Apologies for any confusion/panic, everyone! :-D

**Comment by danielballan** [comment]
Delaying this at least a day, bogged down by Travis-CI problems....

**Comment by danielballan** [comment]
Tagged on GitHub; published on PyPI; conda packages available at anaconda.org/lightsource2-tag; release notes up: https://nsls-ii.github.io/bluesky/api_changes.html
