### ISSUE TITLE
Rename create/save to open_event/close_event

### ISSUE THREAD

**Issue by jrmlhermitte** [NSLS-II/bluesky#991]
After discussion with @danielballan about events in general, he suggested that `bps.create` and `bps.save` be renamed to `bps.open_event` and `bps.close_event`.
I think these make more sense and I second them for the following reasons:
- `bps.create()` could be confused with the creation of a descriptor. Note that it only creates a descriptor on the first event, and otherwise generates events.
- There are cases where we may want to alternate in the creation of events for different streams. I'll give an example we have where we want to have access to a filename before data has finished collecting for example (with pseudo code):
```py
# start triggering the detector
bps.trigger(det, group=grp)
bps.create(name='stream_primary')
# read filename from some file plugin
bps.read(det.fileplugin)
# this emits filename for a long acquisition
bps.save()
# wait for a long data acquisition to complete
bps.wait(group=grp)
bps.create(name='primary')
# now read the filename again, but also other stat plugins device may have
bps.read(det)
bps.save()
```

The naming to `open_event` and `close_event` would help make this clearer. Any thoughts? Thanks!

**Comment by jrmlhermitte** [comment]
I'd be interested to hear from @teddyrendahl @ZLLentz @tacaswell and @CJ-Wright as well.

**Comment by tacaswell** [comment]
I am in general :-1: on changing the names of things (as @danielballan will tell you).  It almost always causes more confusion than it it alleviates and now you have 2 (or more) names for things floating around.

**Comment by danielballan** [comment]
I think that `create` and `save` _should have been_ named `open_event` and `close_event`, but I'm 50/50 on whether adding new names causes more good than harm at this point. I completely defer to the consensus of the group.

**Comment by ZLLentz** [comment]
Are there instances of people getting confused as to what `create` and `save` do? If it creates a usability concern, there is a reason to change. I agree that these are better names, but I'm not convinced the old names are a problem. I expect that most users just call `trigger_and_read` anyway.

**Comment by CJ-Wright** [comment]
I'm meh on this, the new names seem nicer but I don't interface with that level too much currently. @chiahaoliu may have a stronger opinion.

**Comment by teddyrendahl** [comment]
Mostly 👎 . Obviously these are better names but since they are at level where we don't expect our "chemist" I think having the perfect name isn't requisite.

**Comment by jrmlhermitte** [comment]
Sounds good. I think the general consensus is :-1: . I'll close this tomorrow unless anyone has any other opinions. Thanks for the feedback!

**Comment by jrmlhermitte** [comment]
closing, thanks again for feedback!
