### ISSUE TITLE
ENH: Install suspender from plans

### ISSUE THREAD

**Issue by teddyrendahl** [NSLS-II/bluesky#998]
## Expected Behavior

Just like you can install a callback during a plan it would be nice to be able to install a suspender from a plan. There are use cases at SLAC that we will always want a suspender for certain plans and it is annoying to have to strip these things on and off the RunEngine before and after the scan.

## Current Behavior

Suspenders must be installed on the RunEngine itself.

## Possible Solution

New RunEngine message or maybe an uglier extension of the existing `subscribe` and `unsubscribe` functions

**Comment by danielballan** [comment]
Agreed. We recently hit a reason to want `Msg('install_suspender', ...)` as well. I believe we thought of this when suspenders were added in the first place and decided to wait until we actually needed it. The time has come.
